### ISSUE TITLE
How to clarify if worker process is being used

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#107]
Thanks @jart for your continued development on rules_closure.  

This is perhaps just a documentation issue regarding the java worker process, but I'm unsure if my configuration is taking advantage of it.  How to confirm this?  The only relevant JVM process obviously related to bazel, but it does not strike me as a worker.  I'm asking as the `closure_js_*` tasks don't seem to be as fast as I would expect.  I'm at `0.2.2`.

```
$ ps -ef | grep java
  501 51145     1   0  3:30PM ??         1:48.23 bazel(pcj) -server 
-XX:+HeapDumpOnOutOfMemoryError 
-XX:HeapDumpPath=/private/var/tmp/_bazel_pcj/57e9e5d0baeedff3d1c2b20a839969b2 
-Xverify:none
-Djava.util.logging.config.file=/private/var/tmp/_bazel_pcj/57e9e5d0baeedff3d1c2b20a839969b2/javalog.properties 
-Djava.library.path=/var/tmp/_bazel_pcj/install/abd9ee28d8a31141dd2953459e151fbb/_embedded_binaries/embedded_tools/tools/objc:/var/tmp/_bazel_pcj/install/abd9ee28d8a31141dd2953459e151fbb/_embedded_binaries/ 
-Dfile.encoding=ISO-8859-1 
-jar /var/tmp/_bazel_pcj/install/abd9ee28d8a31141dd2953459e151fbb/_embedded_binaries/A-server.jar 
--max_idle_secs 10800 
--install_base=/var/tmp/_bazel_pcj/install/abd9ee28d8a31141dd2953459e151fbb 
--install_md5=abd9ee28d8a31141dd2953459e151fbb 
--output_base=/private/var/tmp/_bazel_pcj/57e9e5d0baeedff3d1c2b20a839969b2 
--workspace_directory=/Users/pcj/my_closure_repo 
--nodeep_execroot 
--nofatal_event_bus_exceptions 
--option_sources=
```

**Comment by jart** [comment]
The flags you want to use are `--worker_verbose --strategy=Javac=worker --strategy=JsChecker=worker`  and that should verify if you are getting the advantage of workers.

**Comment by pcj** [comment]
Great.  I didn't realize I needed to invoke bazel with those arguments.  To summarize:

```
$ ~/bin/bazel build \
  --strategy=Javac=worker \
  --strategy=JsChecker=worker \
  --worker_verbose \
  //src/main/js/pr:util_lib
```

I now have 5 persistent worker processes (yay!):

```
$ ps -ef | grep persistent_worker | wc
5
```

A few observations:

1. If the target is up to date, persistent workers are not launched (this is expected).
2. If the target is a `closure_js_lib` function, persistent workers are launched (expected).
3. If the target is a `closure_js_test`, persistent workers are not used.  Is this expected?  Still takes 22sec to compile and perform a simple test.

**Comment by jart** [comment]
`closure_js_binary` is still going to go super slow. It doesn't use workers and they probably wouldn't help that much anyway, because it's so slow.

The Closure Compiler team is currently working on an incremental compilation feature, which will make things go a lot faster in the future.

**Comment by hochhaus** [comment]
Also, I've found it helpful to put these flags in my `.bazelrc` file. I know this is mentioned in the [java workers bazel blog post](http://www.bazel.io/blog/2015/12/10/java-workers.html) but maybe we should highlight it in `README.md` as well?

**Comment by jart** [comment]
I'm holding off on mentioning it in the readme, because there's a bug in workers which was only fixed quite recently. It doesn't happen when using Bazel normally on my workstation. It only seemed to happen on Travis CI. See:

- https://github.com/bazelbuild/bazel/issues/1330
- https://github.com/bazelbuild/rules_closure/blob/master/.travis.yml#L19

**Comment by hochhaus** [comment]
Thanks for the heads up about that issue.
