### ISSUE TITLE
gensrcjar.sh is not an executable

### ISSUE THREAD

**Issue by gramic** [bazelbuild/rules_closure#113]
I am getting the following error only inside Jenkins. Locally everything works fine.

`___[1 / 4] Creating source manifest for @io_bazel_rules_closure//closure/private:gensrcjar
ERROR: /root/.cache/bazel/_bazel_root/cf8d42d68fca9e0e738d433d5b921ba4/external/io_bazel_rules_closure/closure/private/BUILD:17:1: failed to create symbolic link 'external/io_bazel_rules_closure/closure/private/gensrcjar': file 'external/io_bazel_rules_closure/closure/private/gensrcjar.sh' is not executable.`

Even after `bazel clean --expunge` the error persists. Bazel version is 0.3.0. Rules closure is 0.2.3 (the same is with master). The file [gensrcjar.sh](https://github.com/bazelbuild/rules_closure/blob/master/closure/private/gensrcjar.sh) in  `external/io_bazel_rules_closure/closure/private/gensrcjar.sh` is really NOT executable.

After looking in the [BUILD](https://github.com/bazelbuild/rules_closure/blob/master/closure/private/BUILD) the name of the rule is the same as the srcs file. I thought that this should not be possible, since the label has the same name as the source. Could this be the problem?

**Comment by jart** [comment]
gensrcjar.sh is definitely executable inside the git repository.

If you install bazel from head, does this still happen?

**Comment by jart** [comment]
Re: the naming, the rule has a different name, because it doesn't have the .sh at the end.

**Comment by gramic** [comment]
> gensrcjar.sh is definitely executable inside the git repository.

Yes, it is in the repository, but not in the `external` directory after Bazel starts the build.

> If you install bazel from head, does this still happen?

I didn't install it from head, but did downgrade Bazel to 0.2.3 and it still happens.
We are using Kubernetes with docker images, so it was easy to start everything from scratch and make sure that it works with some version.

The only way to make it work was to downgrade rules_closure to v0.2.2
It seems related to the Bazel worker that you are trying to use.

> Re: the naming, the rule has a different name, because it doesn't have the .sh at the end.

Yes, you are right, my mistake.

**Comment by gramic** [comment]
> The fact that you need to downgrade isn't good. We need to get that fixed.

Downgrading was just to narrow the problem. It is definitely not a solution.

> Does this only happen on Jenkins?

Yes, on my workstation (ubuntu 16.04) it doesn't happen.

> If so, what platform is Jenkins running this on? Does it happen when running it on your workstation?

Jenkins runs on Debian 8.2 which is different then mine. The strange part is that it used to work fine, until we had to use submodules. But this possibility was excluded after some tests.

> Also would it be possible for you to create a minimal project in a zip file that reproduces this error? And then upload it to this bug?

Yes, I am trying to do exactly this.

**Comment by jart** [comment]
Well the thing is, downgrading probably didn't truly solve the problem. If you `bazel build //something:foo_lib` directly (rather than building the _bin target) then it'll probably still fail. Because the only thing v0.2.3 really changed was making sure the build actually happens on that lib target. Even if you're not in the habit of saying `bazel build //something/...`.

**Comment by gramic** [comment]
I managed to reproduce the error in debian jessie with installed dependencies for Bazel 0.3.0 inside Docker container.

My conclusion is that the problem is in Bazel itself, because even with rules_closure 0.2.2 the build of
`bazel build @io_bazel_rules_closure//closure/library` fails with the same error.

The test was simple WORKSPACE file with the [default setup](https://github.com/bazelbuild/rules_closure#setup) content for Closure Rules for Bazel.

Shell I report this problem in the Bazel issues?

**Comment by kchodorow** [comment]
No need, I filed https://github.com/bazelbuild/bazel/issues/1515 :)
