### ISSUE TITLE
override warning_level

### ISSUE THREAD

**Issue by SalzzZ** [bazelbuild/rules_closure#114]
how to override default "--warning_level=VERBOSE"?
I tried adding

```
  defs = [
    "--warning_level=DEFAULT",
  ],
```

but it seems to be ignored.
Manually doing:

```
java -jar v20160713.jar --warning_level VERBOSE -- warning_level DEFAULT ...
```

output the js as expected

**Comment by jart** [comment]
Unfortunately, there is currently no way to do this. Although it's something I've thought about in the past.

It would be very trivial though for us to change [closure_js_binary.bzl](https://github.com/bazelbuild/rules_closure/blob/master/closure/compiler/closure_js_binary.bzl) so it only sets the default value for that flag if one hasn't been provided in `defs`. I would happily merge something like that. Then you could use `git_repository()` to reference this repository until the next release.

**Comment by jart** [comment]
Closing because referenced commit seems to fix this.
