### ISSUE TITLE
closure_js_test doesn't include data files in test

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_closure#116]
This might be working as intended, but I'm using a non-closure JavaScript library (three.js) with closure rules, so I include it in the `data = []` field of my rule.  It shows up in the runfiles, but it isn't linked in any way into the test, so the test fails because it doesn't know to actually load the file three.js.

BUILD file:

```
closure_js_test(
    name = "physical_piece_test",
    srcs = ["physical_piece_test.js"],
    compilation_level = "WHITESPACE_ONLY",
    data = ["//webapp/static/js:three.js"],
    deps = [
        ":physical_piece",
        "@io_bazel_rules_closure//closure/library:testing",
    ],
)
```

Running this, I get:

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
/private/var/tmp/_bazel_kchodorow/bd6c6b17b1b34346312531ebeb8e0794/execroot/fabricate-diem/bazel-out/local-fastbuild/bin/webapp/static/js/cloth/physical_piece_test.runfiles/com_kchodorow_diem
Listening http://localhost:42185/index.html
Serving /index.html
Serving /filez/webapp/static/js/cloth/physical_piece_test_bin.js
Serving /filez/external/io_bazel_rules_closure/closure/testing/phantomjs_jsunit_runner.js
ReferenceError: Can't find variable: THREE
> global code at http://localhost:42185/filez/webapp/static/js/cloth/physical_piece_test_bin.js:6028
```

I ended up modifying the html used for the test, I specified `html = "tester.html"` and made tester.html contain:

```
<meta charset="utf-8">
<head>
  <script type="text/javascript" src="/filez/webapp/static/js/three.js"></script>
</head>
<body>
</body>
```

But it seems like that should happen automatically or something.

**Comment by jart** [comment]
I'm glad the html hack worked out for you. In all fairness, more thought needs to be put into the design of the testing rules. The design of `closure_js_test` isn't going to change much. But `phantomjs_test` is going to change a lot. (Hence why it's marketed as low level in the readme.)

Out of curiosity, did you try creating a `closure_js_library` rule for your three.js file? Then you wouldn't need the html file. And since you're using WHITESPACE_ONLY mode, you probably won't really have to write an externs file or anything fancy.

**Comment by jart** [comment]
Another option that MIGHT work (depending on how the test runner is implemented) is to have a setUp() function in your test that writes the script tag to the dom. For example:

```javascript
goog.require('goog.dom');
goog.require('goog.html.legacyconversions');

/**
 * Adds specified HTML string to document.
 * @param {string} html
 */
function addToDocument(html) {
  goog.global.document.body.appendChild(
      goog.dom.safeHtmlToNode(
          goog.html.legacyconversions.safeHtmlFromString(html)));
}

function setUp() {
  addToDocument('<script ...>');
}
```

**Comment by kchodorow** [comment]
> Out of curiosity, did you try creating a closure_js_library rule for your three.js file? Then you wouldn't need the html file. And since you're using WHITESPACE_ONLY mode, you probably won't really have to write an externs file or anything fancy.

AFAIK, I can't make a closure_js_library rule for three.js, because it straight up doesn't compile. 

(And I don't really want to be using WHITESPACE_ONLY, but I tried to generate an externs file and ran into https://github.com/eredo/tsd2cce/issues/6.)

> Another option that MIGHT work (depending on how the test runner is implemented) is to have a setUp() function in your test that writes the script tag to the dom.

It looks like that almost works, except I have several global variables (e.g., gravity) that are THREE.Vector3s, which are initialized before setUp() is run :(

**Comment by jart** [comment]
TensorFlow actually uses three.js. So in the very near future, I'm going to have to make Closure Rules work correctly with it. It could be as simple as adding `/** @suppress {const} */` to var THREE of version ad419d40bdaab80abbb34b8f359b4ee840033a02.

**Comment by jart** [comment]
Out of curiosity @kchodorow is there any information on what exactly is the difference between the `runfiles`, `default_runfiles`, and `data_runfiles` providers? Also what exactly does `cfg="data"` do? I wasn't able to figure it out by reading the Bazel source code.

I thought I understood before how Bazel propagates data and runfiles up through rules, but now I'm starting to suspect I don't. I'm going to be playing around with things today to see if I can understand Bazel's behavior better with these things. But I would be appreciative if you could help illuminate this mystery.
