### ISSUE TITLE
Allow empty srcs for closure_js_library

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/rules_closure#117]
I'd like to be able to do:

```
closure_js_library(
    name = "tools",
    deps = [":tool1", ":tool2", ":tool3"],
)
```

That way some of my code can have fine-grained dependencies on a certain tool whereas other parts can just depend on "all tools" with a single dep.

Edit: I guess transitive dependencies in general aren't really a thing, is that a limitation of closure or of the rules?_

**Comment by jart** [comment]
Consider using `exports` which works just like it does with `java_library`. ([Docs](https://github.com/bazelbuild/rules_closure#closure_js_library))

**Comment by jart** [comment]
Also I like your whole idea of having a coarse grained entry point into a fine grained dependency graph. One of these days, I might actually break up `//closure/library` into a hundred or so `closure_js_library` rules and then just have `//closure/library` export them all. But so far, nothing has necessitated this.

**Comment by kchodorow** [comment]
> Consider using exports

Yay, that works great!  You might want to soften the language in the README, if that's the recommended solution:

> However this feature should ideally never be used. If you find yourself needing exports, then you may wish to consider refactoring things so it's no longer necessary.

**Comment by jart** [comment]
I agree. I'll do that as soon as I get a chance.

**Comment by jart** [comment]
This was resolved in https://github.com/bazelbuild/rules_closure/commit/fef64e95810c0d9903d2f9f12d69a512a3a737df 25 days ago, but I forgot to close out this bug.
