### ISSUE TITLE
Allow user to disable CSS output source map

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#129]
While updating some of our code to use rules_closure 0.3.0 I ran into https://github.com/google/closure-stylesheets/issues/11. Basically, the CSS compiler crashes with a NullPointerException when source maps are enabled if a property value contains a comma. For example:

```
body {
  font-family: 'Roboto', sans-serif;
}
```

Unfortunately, for me, this is a show stopper for the upgrade. I don't see an easy way for me to disable the source map in the current API. Can we provide an override until this is fixed in the CSS compiler?

**Comment by hochhaus** [comment]
@jart Any time to offer feedback on this?

**Comment by jart** [comment]
I'll try to get a release out today fixing this.
