### ISSUE TITLE
JsChecker error - NumberFormatException

### ISSUE THREAD

**Issue by gramic** [bazelbuild/rules_closure#141]
When building closure_js_binary I got NumberFormatException for one of the closure_js_library inside.
Using --sandbox_debug didn't help.

Is there any way to turn jschecker off or at least see more information for what is parsed?

The exception is attached as [exception.txt](https://github.com/bazelbuild/rules_closure/files/500438/exception.txt)

**Comment by gramic** [comment]
After taking apart a lot of code the error was mine and as stupid as possible.
There was closure_css_bin in the srcs of the closure_js_bin.

**Comment by hochhaus** [comment]
FWIW, `rules_closure()` could be stricter about the allowed inputs in order to help catch these types of mistakes early. @jart Do you think that is worth of a feature request?

**Comment by jart** [comment]
Did it print a Java stacktrace? Could you share it?

**Comment by gramic** [comment]
@hochhaus Stricter rules that catch that type of errors would save a lot of headaches. In that particular case, it seams that better error messages (what file is parsed for example) would have been sufficient.

@jart The stack trace is attach in the first report under this [link](https://github.com/bazelbuild/rules_closure/files/500438/exception.txt).
