### ISSUE TITLE
pedantic mode for closure_js_library()

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#144]
IMO it would be nice to add an (optional) pedantic mode to `closure_js_library()` which converted all WARNINGS to ERRORS.

```
  private static final ImmutableSet<String> WARNINGS =
      ImmutableSet.of(
          "checkTypes",
          "deprecated",
          "deprecatedAnnotations",
          "extraRequire",
          "lintChecks",
          "nonStandardJsDocs");
```

@jart I can't remember, have we talked about this before? Would you be open to such a PR?

**Comment by jart** [comment]
Yeah that's probably a good idea. The thing about warnings is they get cached and don't show up again unless you bazel clean. So we probably shouldn't have them at all in the long run.

**Comment by hochhaus** [comment]
@jart Makes sense. I honestly would prefer to not have any warnings either (instead just errors). As you said, the current setup causes problems since the WARNINGS don't break the build, get cached and are easy to forget. I find myself cleaning frequently to ensure I didn't miss any WARNINGS when instead I should be able to rely on the output of an incremental build.

Would you prefer to see a change (a) converting all WARNINGS to ERRORS or (b) adding a pedantic mode which, when set, upgrades the WARNINGS to ERRORS?

**Comment by jart** [comment]
I would happily merge a change just making everything an error in closure_js_library.
