### ISSUE TITLE
with convention = "NONE", OPTIONAL_TYPE_NOT_USING_OPTIONAL_NAME still occurs

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/rules_closure#157]
My understanding is that the OPTIONAL_TYPE_NOT_USING_OPTIONAL_NAME warning should only be emitted by the Google-style linting. However, I can set `convention = "NONE"` in a closure_js_library that has the error present[1] and the OPTIONAL_TYPE_NOT_USING_OPTIONAL_NAME will be returned.

I think this is a bug JsCheckers whitelisting of the errors.

[1] Invalid code will look like:

```
/**
 * doubles a string
 *
 * @param {string=} something
 * @returns {string}
 */
function double(something) {
  return something + something;
}
```

Notice the lack of an `opt_` prefix in the variable name `something`.

**Comment by jmhodges** [comment]
(I think it's in JsChecker because I was not able to repro in either the 20160822 version of the closure-compiler nor the latest 20160911 version. Both of those I downloaded from this site: https://github.com/google/closure-compiler/wiki/Binary-Downloads)

**Comment by jmhodges** [comment]
Oh, this is, btw, with the current HEAD, 7c7ca69435cd064b81e1f1952e1ab4b360a62921

**Comment by jmhodges** [comment]
Ah, I had a `pedantic = True` in there. Maybe that does it?

**Comment by jmhodges** [comment]
Nah, that wasn't it. Was on a closure_js_binary that just had the erroring file as a dep, anyway.

**Comment by jmhodges** [comment]
Any idea on this one? It's a real bummer when working with 3rd party javascript files.

**Comment by jart** [comment]
Apologies for the delay. Does `suppress = ["OPTIONAL_TYPE_NOT_USING_OPTIONAL_NAME"]` do the trick?

**Comment by jart** [comment]
We honestly need to do more work about defining the boundaries between the various conventions. Right now the convention flag doesn't carry as profound a meaning as it should.

**Comment by jmhodges** [comment]
It does suppress it correctly! Was just surprised that it was needed is all.

Okay, thanks! That's what I expected to be the problem. In that case, this ticket is a mild request for more profundity. I'm sure y'all have a ton of work, so I'm not up in arms about it.

**Comment by jart** [comment]
By the way, the linter is upset because it wants you to put `opt_` in front of the parameter, per Google JavaScript style. For example:

```js
/**
 * doubles a string
 *
 * @param {string=} opt_something
 * @returns {string}
 */
function double(opt_something) {
  return something + something;
}
```

**Comment by jart** [comment]
I really appreciate that you brought this to our attention though. I'm actually going through all our diagnostic codes and figuring out how to divide them all cleanly right now. So this issue is really helpful.

**Comment by MatrixFrog** [comment]
If you're able to use ES6 default values, I believe the linter will not
bother you about the `opt_` prefix:

function double(something = '') {
  return something + something;
}
