### ISSUE TITLE
ES6 imports with ./ do not work

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#160]
What am I doing wrong here?  It seems like this should work based on https://github.com/bazelbuild/rules_closure/tree/master/closure/compiler/test/strict_dependency_checking. As dependency strictness checking is done by rules_closure itself (outside of closure compiler itself), I wonder, did I miss something?

``` js
// app.js
class App {
   sayHello() { return "Hello!"; }
}
export default App;
```

``` js
// main.js
import App from `./app`;
// does not work either:
//import App from `app`;
//import App from `path/to/package/app`;

var app = new App();
app.sayHello();
```

``` sh
ERROR: strictDependencies CR_NOT_PROVIDED - Namespace not provided by any srcs or direct deps of //:main.
import App from './app';
                ^

1 error(s), 0 warning(s)
```

``` python

closure_js_library(
    name = "app",
    srcs = [
        "app.js",
    ],
    deps = [
        "@io_bazel_rules_closure//closure/library",
    ],
    language = 'ECMASCRIPT6_STRICT',
)

closure_js_library(
    name = "main",
    srcs = [
        "main.js",
    ],
    deps = [
        ":app",
        "@io_bazel_rules_closure//closure/library",
    ],
    language = 'ECMASCRIPT6_STRICT',
)

closure_js_binary(
    name = "bin",
    deps = ["main"],
    language = 'ECMASCRIPT6_STRICT',
)
```

Here's another example that I wonder if it would compile with rules_closure: https://github.com/ChadKillingsworth/geolocation-marker/blob/master/src/geolocation-marker.js (@ChadKillingsworth)

**Comment by ChadKillingsworth** [comment]
Does closure_rules understand dependency management other than `goog.provide` and `goog.module`? ES6, CommonJS modules and goog modules are all normalized by the compiler.

**Comment by jart** [comment]
Closure Rules totally supports es6 modules. But it seems you discovered a
bug in CheckStrictDeps.java
<https://github.com/bazelbuild/rules_closure/blob/master/java/com/google/javascript/jscomp/CheckStrictDeps.java>.
That "./" in the path needs to be removed. All es6 module names right now
need to be relative to the root of the repository.

I'm actually working on improving es6 module support right now. One thing
I'm adding is an "includes" attribute to closure_js_library that works just
like it does in cc_library, so you can have paths that aren't relative to
the root. I'm also going to fix that bug.

**Comment by blickly** [comment]
I think that this is a blocker for switching to the BROWSER module-resolution mode, which doesn't allow module names that start with anything other than '/' or '.'

**Comment by jart** [comment]
Let me get on top of this then.

**Comment by ChadKillingsworth** [comment]
Module path names that used to be `some/path/to/module.js` with `LEGACY` would now be `/some/path/to/module.js` with `BROWSER` and you may need to add `--js_module_root` flags if there are additional roots beyond the compilation root.

And of course you have to be able to consume relative paths from one script to another as well.
