### ISSUE TITLE
es6 test case

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#163]
Is it possible to use `closure_js_test` with es6?  If so, can someone provide an example?

**Comment by jart** [comment]
Here's an example of using es6 with es6 imports along with closure_js_test

https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/test/arithmetic_es6module_test.js
https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/test/BUILD#L68

**Comment by jart** [comment]
Marking as closed. Let me know if this isn't resolved and I'll re-open it.

**Comment by pcj** [comment]
Running a trivial es6 test case is OK, but when you want to use `const Foo = goog.require('a.b.c.Foo')`, it must be in a `goog.module`.  When that occurs, `test*` functions are no longer in global namespace and can't be autodiscovered.  

Here's a first example for a module-enclosed test that actually passes.  Seems like there's must be a better way...

```python

closure_js_test(
    name = "es6_module_test",
    srcs = [
        "es6_module_test.js",
    ],
    deps = [
        "@io_bazel_rules_closure//closure/library:testing",
    ],
    entry_points = ["goog:closure.ModuleTest"],
    language = 'ECMASCRIPT6_STRICT',
)
```

```javascript
goog.module('closure.ModuleTest');
goog.setTestOnly();

const TestCase = goog.require('goog.testing.TestCase');
const TestRunner = goog.require('goog.testing.TestRunner');

class ModuleTest extends TestCase {
  constructor() {
    super('ModuleTest');
    this.addNewTest('testAddition', this.testAddition, this);
  }

  testAddition() {
    console.log('testAddition is running!');
    assertEquals(2, 1 + 1);
  }

}

/** @type {!goog.testing.TestRunner} */
var runner = new TestRunner();
runner.initialize(new ModuleTest());
runner.execute();

// Required to satisfy the phantomjs test runner
window['G_testRunner'] = {
  'isFinished': () => { return runner.isFinished(); },
  'isSuccess': () => { return runner.isSuccess(); }
};
```

**Comment by jart** [comment]
Does it help if you say:

exports = ModuleTest


At the bottom of the file?

**Comment by pcj** [comment]
Looks like compiler eliminates the test case as dead code, no trace of it in the generated _test_bin.js file.
 
```javascript
goog.module('closure.ModuleTest');
goog.setTestOnly();

const TestCase = goog.require('goog.testing.TestCase');
//const TestRunner = goog.require('goog.testing.TestRunner');

class ModuleTest extends TestCase {
  constructor() {
    super('ModuleTests');
    this.addNewTest('testAddition', this.testAddition, this);
  }

  testAddition() {
    console.log('testAddition is running!');
    assertEquals(2, 1 + 1);
  }

}

// /** @type {!goog.testing.TestRunner} */
// var runner = new TestRunner();
// runner.initialize(new ModuleTest());
// runner.execute();

// window['G_testRunner'] = {
//   'isFinished': () => { return runner.isFinished(); },
//   'isSuccess': () => { return runner.isSuccess(); }
// };

exports = ModuleTest;
```

**Comment by jart** [comment]
In order to have a module be a test you need to use goog.testing.testSuite

Here's an example:
https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/test/arithmetic_module_test.js

**Comment by pcj** [comment]
Ahhhhh.  Don't know how I missed that. Thank you!
