### ISSUE TITLE
Angular2 Example

### ISSUE THREAD

**Issue by colemickens** [bazelbuild/rules_closure#166]
Is this capable of building angular2 projects? Is there an example project that uses rules_closure to build an angular2 project that I could look at?

**Comment by jart** [comment]
Isn't Angular2 built off TypeScript?

**Comment by jart** [comment]
I know we have users who successfully use Angular1, but I'm not sure about Angular2. AFAIK Angular2 switched from JavaScript to TypeScript. Closure Rules doesn't build TypeScript. @mprobst has been working on creating TypeScript rules for Bazel, but I'm not sure when that's going to happen. Incorporated anything Nodejs related into Bazel poses certain challenges that are not easy to overcome. You might want to consider tools like Gulp and NPM instead.

**Comment by mprobst** [comment]
There is currently no open source example using Angular 2 + TypeScript + bazel, sorry. We're interested in providing that (and hooking it up with `rules_closure`), but that's still a ways out. We'll announce & share on twitter once we have something usable.

**Comment by jart** [comment]
Thanks for the information @mprobst. I'm going to close this one out.
