### ISSUE TITLE
Revert README to latest release

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/rules_closure#180]
Setting the language_in the defs attribute on the closure_js_binary rule does not work.

```shell
$ blaze build :hello_bin
INFO: Found 1 target...
ERROR: /home/joe/tmp/closureBug/BUILD:4:1: Checking 1 JS files in //:hello failed: Worker process sent response with exit code: 1.
lib.js:1: ERROR - this language feature is only supported for ECMASCRIPT6 mode or better: template literal. Use --language_in=ECMASCRIPT6 or ECMASCRIPT6_STRICT to enable ES6 features.
console.log(`hello world`);
            ^

1 error(s), 0 warning(s)

Target //:hello_bin failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.128s, Critical Path: 0.01s

```

Directory structure
```
├── BUILD
├── lib.js
└── WORKSPACE
```

BUILD
```python
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_binary")
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

closure_js_library(
    name = "hello",
    srcs = ["lib.js"],
)

closure_js_binary(
    name = "hello_bin",
    deps = [":hello"],
    defs = [
        "--language_in=ECMASCRIPT6_STRICT",
    ],
)
```

lib.js
```js
console.log(`hello world`); # template literal strings
```

WORKSPACE
```python
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "b8c6dfea8ad3e691037b7eeecf5ab18ae39b74a51ff74c377d4f5eff97c894f4",
    strip_prefix = "rules_closure-0.4.0",
    url = "http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/0.4.0.tar.gz",
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")

closure_repositories()
```

**Comment by hochhaus** [comment]
I should have also mentioned, at release v0.4.0 closure_js_library still contained a `langauge` argument which is likely overriding your setting.

You might want to check out this version of the README for 0.4.0:

https://github.com/bazelbuild/rules_closure/blob/a072e282ee22935d1e43f78b60f4b702688fa801/README.md#closure_js_library

At HEAD (not recommended) the default version has been set to ES6 and thus was removed from the README.

**Comment by jschaf** [comment]
Oh, I missed the language setting on the library rule.  Thank you.

**Comment by jart** [comment]
I'm re-opening because I still think this is actionable on our part. We should probably revert the README changes that have occurred since the last release. We don't want users to run into any surprises.

**Comment by jart** [comment]
Eventually we're going to put the time into building a separate GitHub Pages website for documentation, so the documentation changes inside the repository don't end up causing these sorts of problems.
