### ISSUE TITLE
phantomjs.sh not found

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/rules_closure#19]
I've found the following in the error log when running `bazel test` for `closure_js_test` rules:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
{test file}: 2: exec: third_party/phantomjs/phantomjs.sh: not found
```

**Comment by wolfgangmeyers** [comment]
I've found that this file is present in the bazel-bin folder:
`bazel-bin/{test file}.runfiles/external/io_bazel_rules_closure/third_party/phantomjs/phantomjs.sh`

**Comment by wolfgangmeyers** [comment]
Looks at first glance like the error originates here (https://github.com/bazelbuild/rules_closure/blob/master/closure/testing/closure_js_test.bzl#L77):
```python
ctx.file_action(
      executable=True,
      output=ctx.outputs.executable,
      content="\n".join([
          "#!/bin/sh",
          "exec third_party/phantomjs/phantomjs.sh \\",
          "  %s \\" % ctx.file._phantomjs_runner.short_path,
          "  %s" % ctx.outputs.js.short_path,
          "",
      ]))
```

**Comment by wolfgangmeyers** [comment]
My guess is that `external/io_bazel_rules_closure` needs to be prepended to the path of phantomjs.sh. I'll test this out and let you know.

**Comment by wolfgangmeyers** [comment]
Well it looks like phantomjs.sh also needs this prepended somewhere:
```
external/io_bazel_rules_closure/third_party/phantomjs/phantomjs.sh: line 38: {test file}.runfiles/third_party/phantomjs/bin/phantomjs: No such file or directory
```

**Comment by wolfgangmeyers** [comment]
hmm, looks like this change broke the tests:
```
bazel-out/host/bin/third_party/phantomjs/phantomjs: line 38: bazel-out/host/bin/third_party/phantomjs/phantomjs.runfiles/external/io_bazel_rules_closure/third_party/phantomjs/bin/phantomjs: No such file or directory
```

**Comment by jart** [comment]
How are you running this?

**Comment by jart** [comment]
How would I reproduce this?

**Comment by wolfgangmeyers** [comment]
I'll get you a minimal project shortly.

**Comment by jart** [comment]
What is the command you are running on the shell though, that produces this error?

**Comment by wolfgangmeyers** [comment]
[phantomjs-path-issue.zip](https://github.com/bazelbuild/rules_closure/files/188633/phantomjs-path-issue.zip)

**Comment by wolfgangmeyers** [comment]
Unzip, and run `bazel test //test` to reproduce. The log file should contain this:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
test/test: 2: exec: third_party/phantomjs/phantomjs.sh: not found
```

**Comment by jart** [comment]
Would it fix things if you added something like runfile dir locator? https://github.com/bazelbuild/rules_closure/blob/master/third_party/phantomjs/phantomjs.sh#L21

I'm unable to reproduce this at the moment. BitBucket appears to be down, so Bazel can't download PhantomJS. 

```
<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Expires>2016-03-24T23:16:18Z</Expires><ServerTime>2016-03-24T23:19:26Z</ServerTime><RequestId>B910187EFE658C75</RequestId><HostId>i19hEak8HxdKEI7IY71pSRx5u5m/kr8OQXV/OKzQQlv0vcL151b2I9YnzAiqSK9BobI4QWgO0Vk=</HostId></Error> and referenced by '@io_bazel_rules_closure//third_party/phantomjs:phantomjs_bin'.
```

I'll try again tomorrow.

**Comment by wolfgangmeyers** [comment]
I've seen this error pop up on occasion in the CI builds.

**Comment by jart** [comment]
I'm talking to people to see if we can get a GCS bucket set up with nearline storage for mirroring these large files.

**Comment by wolfgangmeyers** [comment]
I'm not an expert in bash, but if we could detect if "external" were present in the absolute path of the file being run it might be a good indicator of whether the rule was running locally within the project or had been imported from another project. This would need to be done in both the closure_js_test rule definition and in the phantomjs.sh script.

**Comment by jart** [comment]
Did you take a look at the code I linked? That complicated if statement basically does trickery like that, to discover the root of the runfiles directory.

**Comment by wolfgangmeyers** [comment]
I did, but I don't fully comprehend the syntax :)

**Comment by jart** [comment]
Getting good at bash really pays dividends. I strongly recommend learning as much as you can. It's the fastest way to automate anything.

**Comment by wolfgangmeyers** [comment]
True. Here is my latest fix for closure_js_test, it works in both the tests and as an imported rule now: https://github.com/bazelbuild/rules_closure/pull/23

**Comment by wolfgangmeyers** [comment]
Still fails after merge of #33
