### ISSUE TITLE
Proto libraries with dependencies

### ISSUE THREAD

**Issue by wiktortomczak** [bazelbuild/rules_closure#190]
Is there a way to generate a JS proto library from a .proto file with dependencies (on other .proto files that the top-level .proto imports) ? IIUC [closure_js_proto_library](https://github.com/bazelbuild/rules_closure#closure_js_proto_library) does not support a deps= argument. I suppose it could?

I believe the implementation of closure_js_proto_library(deps=...) could rely on the [proto_library](https://bazel.build/blog/2017/02/27/protocol-buffers.html) rule added to Bazel recently.

**Comment by rohanag12** [comment]
Is there any plan on supporting this feature? Also, is there some workaround we can use for this (other than bundling statically generated files, of course)?

**Comment by shubhangitaneja** [comment]
Ability to specify deps in closure_js_proto_library would be definitely helpful. My proto is importing "google/protobuf/timestamp.proto" and right now I don't see any way to specify a dependency on it.

**Comment by pshields** [comment]
I've run into a similar issue. The protos I'm compiling import `google/api/annotations.proto`. I tried adding that file and its deps as a filegroup passed to `srcs` (in addition to my regular `srcs`), but ran into additional errors. I think being able to specify deps via a `deps` parameter would help. At the very least, it would be more idiomatic.

Incidentally, if I strip out my  `google/api/annotations.proto` import and related code, my `closure_js_proto_library` rule is able to build successfully and is able to resolve my `google/protobuf/timestamp.proto` imports.
