### ISSUE TITLE
error in bazel/ tensorflow installation 'external:io_bazel_rules_closure: no such attribute 'urls' in 'http_archive' rule.'

### ISSUE THREAD

**Issue by asokraju** [bazelbuild/rules_closure#191]
Hi all I am trying to install tensor flow with GPU compatibility using this guide "guide [1"](http://textminingonline.com/dive-into-tensorflow-part-iii-gtx-1080-ubuntu16-04-cuda8-0-cudnn5-0-tensorflow) and[ guide  2 ](http://www.computervisionbytecnalia.com/en/2016/06/deep-learning-development-setup-for-ubuntu-16-04-xenial/)on ubuntu pc (cuda 8). I am stuck at installing tensorflow, when I use `./configure`, I getting this error.

`ERROR: /home/krishna/tensorflow/WORKSPACE:3:1: //external:io_bazel_rules_closure: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/krishna/tensorflow/WORKSPACE:3:1: //external:io_bazel_rules_closure: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': error loading package 'external': Could not load //external package.`

I am new to ubuntu, after reading a lot I understood that, the error has something to do with "[version of bazel](https://github.com/tensorflow/tensorflow/issues/7433)" (for version above 0.3.1 it does not apper). When I use the command

```
$bazel version

Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```
when i use

```
$ sudo apt-get install bazel
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    bazel is already the newest version (0.4.5).
    0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```
and upgraded it using  `$ sudo apt-get upgrade bazel`. Finally I tried

```
$ bazel version
Build label: 0.3.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 10 11:38:23 2016 (1465558703)
Build timestamp: 1465558703
Build timestamp as int: 1465558703
```
which shows me that I am at version 0.3.0. I even tried compiling tensorflow again,which gave me the same above error.

**Comment by pcj** [comment]
That's a somewhat old version of bazel.  I don't think TF supports the most bleeding edge version of bazel either, so try something around 0.4.4 and/or post to bazel-discuss for additional help.

**Comment by ausk** [comment]
I also get the same error when compile the tensorflow document. Then I check my bazel version, it's 0.4.1. As other guys said, tensorflow and bazel are update so fequency, and the new versions do not support the deprecated fucntions.
So when the bazel is updated to the latest version (current is 0.4.5) in the command " sudo update bazel",  all become normal.

**Comment by jart** [comment]
0.4.2 is when the new downloader was introduced. Closure Rules at HEAD requires Bazel ≥0.4.5.

If possible, we recommend using the release tagged version of Closure Rules available [here](https://github.com/bazelbuild/rules_closure#setup) because HEAD is still experimental. The tagged release should support Bazel versions back to 0.3.2.
