### ISSUE TITLE
Add --force_inject_library flag

### ISSUE THREAD

**Issue by kaspnilsson** [bazelbuild/rules_closure#199]
I'd like to add the flag added to the Closure Compiler in [this commit](https://github.com/google/closure-compiler/commit/d5e0c84f57aeba1126d8859d7df93845e776d1f3) as a whitelisted dep. 
How should I go about doing that?

**Comment by kaspnilsson** [comment]
Looks like what I need to do is upgrade the version of the Closure Compiler to https://github.com/google/closure-compiler/releases/tag/v20170423

**Comment by jart** [comment]
I can update the release to the latest version of Closure Compiler shortly.

**Comment by davido** [comment]
Seems like this was done already and can be closed.

**Comment by jart** [comment]
Ah yes thank you for the heads up.
