### ISSUE TITLE
Remove '-client' JVM flag from repositories.bzl

### ISSUE THREAD

**Issue by brunoalr** [bazelbuild/rules_closure#208]
Tensorflow currently does not build on ppc64le since the -client flag is set on this repository on repositories.bzl. Is it strictly needed? Should different targets be treated differently?

Please take a look at this [answer](https://stackoverflow.com/questions/44376101/checking-architecture-with-bazel-skylark/44392124#44392124).

**Comment by brunoalr** [comment]
@katre please take a look here.

**Comment by jart** [comment]
We can remove the -client flag. I mailed out a change to do that now.

**Comment by brunoalr** [comment]
Thanks! :)
