### ISSUE TITLE
include uncompiled javascript files for closure_js_test

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/rules_closure#21]
I need to write tests that have a runtime dependency on angular. I've tried including angular in deps and compiling it but the end result seems to be mangled code. Can we add a way for the test runner to load libraries that are non-compatible with closure before the test files?

**Comment by jart** [comment]
What's wrong with mangled code? Do the tests run when you link Angular in?

A possible fix would be my proposal in #6. If you could specify a foo_test_dom.html file, then you could put a script tag for angular in there. It might also be worthwhile if there was a "dom" argument to closure_js_test that allowed you to inline the HTML into the build rule.

**Comment by jart** [comment]
Right now, all code that gets run by closure_js_test is technically mangled, because ariya/phantomjs/issues/14028 prevents us from running tests in "raw sources mode." So we have no choice but to run all the .js files through the Closure Compiler and have it output a binary blob that's pretty printed and WHITESPACE_ONLY.

**Comment by wolfgangmeyers** [comment]
That makes sense.  I don't have anything against mangled code, if it works - but the test blows up when I link Angular in. Being able to specify a dom file sounds like it would work.

**Comment by jart** [comment]
Define "blows up." Could you copy and paste some of the errors?

**Comment by wolfgangmeyers** [comment]
Listening http://localhost:39558/index.html
Serving /index.html
Serving /filez/assets/tests/{test file}_dbg.js
TypeError: undefined is not an object (evaluating 'f.module')
> http://localhost:39558/filez/assets/tests/{test file}_dbg.js:6695

Lines 6694-6696 of {test file}_dbg.js:

(function(N, f, W) {
  f.module("ngAnimate", ["ng"]).directive("ngAnimateChildren", function() {
    return function(X, C, g) {

**Comment by jart** [comment]
This is very interesting. That should not be happening. Can you create a zip for me that reproduces this? I'll take a look tomorrow.

**Comment by wolfgangmeyers** [comment]
So I carefully listed the angular js files in a different order, and now have a different behavior.

```
-> TypeError: undefined is not a function (evaluating 'angular.mock.module("{angular module}")') undefined is not a function (evaluating 'angular.mock.module("{angular module}")') setUp@http://localhost:50235/filez/assets/tests/{test file}_dbg.js:17313:22
```
I'll work on getting you a zip. It will need to use my fork in order to work around https://github.com/bazelbuild/rules_closure/issues/19

**Comment by jart** [comment]
Yes you definitely have to make sure that the partial ordering of dependencies constructed by the build system is correct, since the strict dependency checker can't check non-Closure namespaces.

**Comment by jart** [comment]
One way to do that is by adding a `print(args)` statement to to `closure_js_test()` to make sure that the angular.js file is first on the list.

**Comment by wolfgangmeyers** [comment]
I've concluded that this isn't an issue with the compiler or with closure_js_test. Changing the order of the files solved the issue. The new issue is due to the fact that angular.mock.module is only ever defined if jasmine is being used as the test framework.
