### ISSUE TITLE
Consider to fix EP warnings

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_closure#211]
When building Gerrit Code Review that (since recently) depends on `rules_closure` and using patched Bazel version with my fix to activate all EP warnings: [1], many warnings are issued for `rules_closure`, that makes it harder to actually see (and fix) EP warnings for gerrit project. Consider to fix EP warnings for this project: [2].

To reproduce, clone gerrit from https://gerrit.googlesource.com/gerrit, apply the bazel patch mentioned below, and execute:

```
  $ <path-to-patched-bazel>/bazel build gerrit
```

and watch for EP warnings that are starting with `external/io_bazel_rules_closure`, e.g.:

```
INFO: From Building external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/libbuild_info_java_proto.jar (1 source jar) [for host]:
/io/bazel/rules/closure/webfiles/BuildInfo.java:775: warning: [FunctionalInterfaceClash] When passing lambda arguments to this function, callers will need a cast to disambiguate with: GeneratedMessageV3.newBuilderForType(BuilderParent)
    protected Builder newBuilderForType(
                      ^
      AbstractMessage.newBuilderForType(BuilderParent)
    (see http://errorprone.info/bugpattern/FunctionalInterfaceClash)
[...]
```

* [1] https://bazel-review.googlesource.com/7891
* [2] http://paste.openstack.org/show/614244

**Comment by MatrixFrog** [comment]
It looks like that's a generated file so maybe the tool generating that code can emit a suppression.

**Comment by davido** [comment]
That would be great.

**Comment by davido** [comment]
(Partially) fixed in: [1].

* [1] https://github.com/google/protobuf/pull/4240
