### ISSUE TITLE
0.4.2 maintenance release

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#219]
It has been a bit since `rules_closure` has had a release. I know HEAD isn't in a position to be released, but could a 0.4.2 maintenance release be considered to update the upstream closure deps?

**Comment by jart** [comment]
Done. https://github.com/bazelbuild/rules_closure/releases/tag/0.4.2

**Comment by hochhaus** [comment]
Huge thanks @jart!
