### ISSUE TITLE
Failing with bazel 0.6

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_closure#224]
When using the Closure rules with Bazel 0.6, I get this error:

```
ERROR: /usr/local/google/home/laurentlb/.cache/bazel/_bazel_laurentlb/1cf9e271f53a4fcee3da31675bf7c3a0/external/io_bazel_rules_closure/closure/private/defs.bzl:32:16: The `set` constructor for depsets is deprecated and will be removed. Please use the `depset` constructor instead. You can temporarily enable the deprecated `set` constructor by passing the flag --incompatible_disallow_set_constructor=false
```

Workaround is simple (specify `--incompatible_disallow_set_constructor=false`), but it would be nice to update the code. Ideally, it would build even with `--all_incompatible_changes`. See https://docs.bazel.build/versions/master/skylark/backward-compatibility.html for background.

Let me know if you need help.

**Comment by jart** [comment]
Which version of Closure Rules are you using? The latest release and HEAD should both have set removed. I've also been updating the WORKSPACE files of dependent projects today to remove references to old pinned versions.

**Comment by laurentlb** [comment]
I just copied the setup code from the readme (https://github.com/bazelbuild/rules_closure#setup).
Glad to hear it was already fixed!

**Comment by calebegg** [comment]
What's the correct way to install this project? I followed the steps in the README and I get the same error.

**Comment by calebegg** [comment]
Ah, I guess there's a modified version of that block under releases. The README should maybe just point to releases.
