### ISSUE TITLE
protoc is broken on non glibc system (Alpine Linux)

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_closure#228]
I'm trying to build Gerrit Code Review on Alpine Linux docker image using latest bazel version: 0.8.0rc1. Here is the Dockerfile: [1].

After booting the docker image, and trying to build Gerrit Code Review master, it is failing in `closure_rules` because its hard coded dependency on `glibc` based `protoc` library:

```
$ bazel build polygerrit
[...]
ERROR: /home/davido/.cache/bazel/_bazel_davido/a6c7865269edc177ebab9d4cd9db0bb3/external/io_bazel_rules_closure/java/io/bazel/rules/closure/worker/BUILD:38:1: error executing shell command: 'JAR='external/local_jdk/bin/jar' OUTPUT='bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/worker/libworker_protocol_java_proto_srcjar.srcjar' PROTO_COMPILER='external/...' failed (Exit 1)
bazel-out/host/bin/external/io_bazel_rules_closure/closure/private/gensrcjar: line 1: external/com_google_protobuf_protoc/bin/protoc: not found
gensrcjar: proto_compiler failed
Target //:polygerrit failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.338s, Critical Path: 0.10s
FAILED: Build did NOT complete successfully
```

The root cause, is that `external/com_google_protobuf_protoc/bin/protoc` cannot be executed on Alpine Linux, because it is based on `musl libc` and not `glibc`.

```
 ldd external/com_google_protobuf_protoc/bin/protoc
	/lib64/ld-linux-x86-64.so.2 (0x7ff35e6f5000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7ff35e6f5000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff35e6f5000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7ff35e6f5000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by external/com_google_protobuf_protoc/bin/protoc)
Error relocating external/com_google_protobuf_protoc/bin/protoc: __isnan: symbol not found
Error relocating external/com_google_protobuf_protoc/bin/protoc: __isnanf: symbol not found
86523ee72618:~/.cache/bazel/_bazel_davido/a6c7865269edc177ebab9d4cd9db0bb3/execroot/gerrit$ ldd protoc
ldd: cannot load protoc: No such file or directory
```

Similar issue was reported here: [2].

It worth noting, that Alpine Linux [provides](https://pkgs.alpinelinux.org/package/edge/main/x86/protobuf) native `protobuf` package:

```
bash-4.3# apk add protobuf
(1/1) Installing protobuf (3.1.0-r1)
Executing busybox-1.26.2-r7.trigger
OK: 558 MiB in 96 packages
bash-4.3# protoc
Missing input file.
```

* [1] https://github.com/davido/bazel-build-gerrit/blob/master/Dockerfile
* [2] https://github.com/tensorflow/tensorflow/issues/103

**Comment by jart** [comment]
Alpine Linux appears to be for embedded systems. Is it necessary to support to be able to run Bazel on these types of systems? Couldn't the compilation be performed on a different system?

**Comment by davido** [comment]
This is a valid question. Docker selected this distribution because of its size. We are providing and using gerrit build slaves based on Ubuntu and noticing that it really huge, compared to Alpine Linux. See this discussion on gerrit-review for more context: [1].

So we would like to switch from using Ubuntu as base image to very small distro like Alpine Linux. The difference of building the Alpine based image compared to Ubuntu both in term of time and size is very impressive.

[1] https://gerrit-review.googlesource.com/c/gerrit-ci-scripts/+/102155?polygerrit=1

**Comment by jart** [comment]
The Ubuntu Docker image is 188MB which isn't unreasonable. I'd recommend the Debian one which is 125MB. It's very impressive that Alpine is 5MB. 

Please understand that while rules_closure downloads and builds incredibly fast and meets the requirements of the largest repositories in the world, it's not exactly 5MB scale. The jar for the Closure Compiler alone is about 3MB. Closure Rules probably downloads at least another 10MB or so of jars. Even more if you're doing things like PhantomJS testing.

Is there any chance you would consider Debian? I'm not sure if I would have any way to promise compatibility with a 5MB Linux distro.

**Comment by davido** [comment]
It turns out, there is a workaround (or better to say a hack) to install `glibc` package on `musl libc` system: [1]. After doing it, gerrit build worked on Alpine Linux.

* [1] https://github.com/sgerrand/alpine-pkg-glibc

**Comment by jart** [comment]
Good to know the Closure Rules work well on embedded system containers, so long as libc is installed. I guess following best practices makes good things happen. Thanks for bringing this news to our attention.
