### ISSUE TITLE
No such package 'closure/templates'

### ISSUE THREAD

**Issue by jacobcui** [bazelbuild/rules_closure#24]
Hi,

For simplest soy building, I met following error:

ERROR: /Users/jacob/projects/feedbacker/src/assets/test/BUILD:32:1: no such package 'closure/templates': BUILD file not found on package path and referenced by '//:hello_soy'.
ERROR: Loading failed; build aborted.

Following are my files, is there anything that I missed?

WORKSPACE:
```
git_repository(
    name = "io_bazel_rules_closure",
    remote = "https://github.com/bazelbuild/rules_closure.git",
    tag = "0.0.1",
)
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()
```

BUILD:
```
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_template_js_library")
closure_template_js_library(
    name = "hello_soy",
    srcs = ["hello.soy"]
)
```
hello.soy:
```
{namespace hello.templates autoescape="strict"}

/**
 * Renders an element containing the text "hello".
 */
{template .hello}
  <div class="{css hello-container}">Hello.</div>
{/template}
```
hello.js:
```
goog.provide('hello');

goog.require('goog.soy');
goog.require('hello.templates');

goog.soy.renderElement(document.body, hello.templates.hello);
```
hello.gss:
```
hello.gss

.hello-container {
  color: red;
  font-weight: bold;
}
```

**Comment by jart** [comment]
Are you using Bazel installed from the latest git version?

**Comment by jacobcui** [comment]
Yes I'm having the bazel from latest git and compiled on my mac.

**Comment by jart** [comment]
If you copied [closure_template_js_library.bzl](https://github.com/bazelbuild/rules_closure/blob/master/closure/templates/closure_template_js_library.bzl) into your own workspace, and referenced it from there, would it work?

It's possible that since this is a macro rather than a build rule, the recent fix for bazelbuild/bazel/issues/975 doesn't apply.

**Comment by jacobcui** [comment]
Copying  closure_template_js_library.bzl into my own workspace didn't work either. I tried following copy/or link rules_closure/closure into my workspace, and changed the reference in WORKSPACE and BUILD. However I gets the 'cycle in dependency' error:

WORKSPACE:
```
load("//closure:defs.bzl", "closure_repositories")
closure_repositories()
```


BUILD:
```
load("//closure:defs.bzl", "closure_js_binary")
load("//closure:defs.bzl", "closure_js_library")
load("//closure:defs.bzl", "closure_css_library")
load("//closure:defs.bzl", "closure_css_binary")
load("//closure:defs.bzl", "closure_template_js_library")

closure_js_binary(
    name = "hello",
    deps = [":hello_lib"],
)

closure_js_library(
    name = "hello_lib",
    srcs = ["hello.js"],
    deps = [
        ":hello_css",
        ":hello_soy",
    ]
)

closure_css_library(
    name = "hello_css",
    srcs = ["hello.gss"]
)

closure_template_js_library(
    name = "hello_soy",
    srcs = ["hello.soy"]
)
```

Then run ```bazel build //:hello```

The results are
```
ERROR: BUILD:8:1: in closure_js_binary rule //:hello: cycle in dependency graph:
  * //:hello
    //:hello_lib
    //:hello.js
  * //:hello.
ERROR: Loading of target //:hello failed; build aborted.
ERROR: Loading failed; build aborted.
```

**Comment by jart** [comment]
I really appreciate the troubleshooting work you've done so far. Is there any chance you can zip up what you've done so I can run it myself and reproduce the error?

**Comment by jacobcui** [comment]
Sure, please find the zip file.
[test.zip](https://github.com/bazelbuild/rules_closure/files/190761/test.zip)

**Comment by jart** [comment]
OK I see what's wrong. Your `closure_js_binary` rule needs to be renamed `hello` -> `hello_bin` because right now it has an implicit output target that overlaps with `hello.js`.

It's also worth mentioning that, at the moment, a JS library rule can't depend on a CSS library rule. That feature hasn't been implemented yet, despite the documentation. But that feature only exists really for checking. So it doesn't impact functionality if you don't link them together. It still works.

**Comment by jart** [comment]
This appears to be about as resolved as it can get. Please let me know if there's anything more I can do.

**Comment by jacobcui** [comment]
Thanks @jart that works! I would say the guide on http://bazel.io/docs/be/closure.html needs updates as it may frustrate new users. Cheers!

**Comment by jart** [comment]
Yeah we're planning on deleting that. This repository is sort of a rewrite of the old rules, and the design has changed a bit.
