### ISSUE TITLE
`goog.net.NetworkTester` should be included in `@com_google_javascript_closure_library//:js_library_files`

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#244]
I am porting some code that uses [goog.net.NetworkTester](https://github.com/google/closure-library/blob/master/closure/goog/net/networktester.js) to `rules_closure` however `@io_bazel_rules_closure//closure/library` does not appear to provide that namespace. Despite the filename, this is not testing code but instead provides network testing functionality for potential use from a production setting.

Possibly [this exclude](https://github.com/bazelbuild/rules_closure/blob/master/closure/library/closure_library.BUILD#L1015) should be tightened such that `closure/goog/net/networktester.js` is included in the library?

**Comment by jart** [comment]
Sure I can probably get that in there for you tomorrow.

**Comment by hochhaus** [comment]
Thanks @jart. You are amazing!

**Comment by jart** [comment]
Just pushed a bunch of maintenance commits. Might take one more day to get the change approved to close this one out.
