### ISSUE TITLE
CI failure on MacOS

### ISSUE THREAD

**Issue by dslomov** [bazelbuild/rules_closure#247]
Bazel 0.9.0: https://ci.bazel.build/blue/organizations/jenkins/rules_closure/detail/rules_closure/969/pipeline/
Bazel nightly: https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_closure/detail/rules_closure/364/pipeline/

**Comment by buchgr** [comment]
friendly ping.

This test is failing:
```
//closure/testing/test:noto_fonts_render_as_expected
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
ERROR: FILES DO NOT HAVE EQUAL CONTENTS
closure/testing/test/fontdemo-darwin.png 0e48c707ba6f0054b946190eb8666fd60a7ae90a
closure/testing/test/fontdemo-generated.png 2727a2893471bac604ebadcaa0d0e0717c75f325
```

Any thoughts?

**Comment by pcj** [comment]
See also https://github.com/bazelbuild/rules_closure/pull/186#issuecomment-279115018.  May want to remove this test @jart?
