### ISSUE TITLE
Bazel warning: external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf) does not match

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_closure#248]
Protobuf uses name: "com_google_protobuf", in its `WORKSPACE` [file](https://github.com/google/protobuf/blob/master/WORKSPACE#L1). `rules_closure` renames this name with `com_google_protobuf_java` (and `_js`) suffix in `closure/repositories.bzl`:

```
def com_google_protobuf_java():
  native.http_archive(
      name = "com_google_protobuf_java",
      sha256 = "0cc6607e2daa675101e9b7398a436f09167dffb8ca0489b0307ff7260498c13c",
      strip_prefix = "protobuf-3.5.0",
      urls = [
          "https://mirror.bazel.build/github.com/google/protobuf/archive/v3.5.0.tar.gz",
          "https://github.com/google/protobuf/archive/v3.5.0.tar.gz",
      ],
  )

def com_google_protobuf_js():
  native.new_http_archive(
      name = "com_google_protobuf_js",
      urls = [
          "https://mirror.bazel.build/github.com/google/protobuf/archive/v3.5.0.tar.gz",
          "https://github.com/google/protobuf/archive/v3.5.0.tar.gz",
      ],
      sha256 = "0cc6607e2daa675101e9b7398a436f09167dffb8ca0489b0307ff7260498c13c",
      strip_prefix = "protobuf-3.5.0/js",
      build_file = str(Label("//closure/protobuf:protobuf_js.BUILD")),
  )
```

This causes this [warning](https://bugs.chromium.org/p/gerrit/issues/detail?id=8182):

```
WARNING: /private/var/tmp/_bazel_xxx/4e4bb427cd475349ab3944ff29048468/external/com_google_protobuf_java/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_xxx/4e4bb427cd475349ab3944ff29048468/external/com_google_protobuf_java/WORKSPACE (@com_google_protobuf)
does not match the name given in the repository's definition (@com_google_protobuf_java);
this will cause a build error in future versions
```

on recent Bazel versions.

**Comment by jart** [comment]
rules_closure recently moved from depending on protobuf release binaries to depending on the protobuf directly. This has improved rules_closure's compatibility in the Bazel ecosystem. However it came various costs.

Like all builds, protobuf has opportunities for improvement. It also bakes its unique perspective on naming into Bazel core. I made an effort to be helpful one year ago advising against these decisions. Perhaps these teams understand things I don't.

Please redirect feedback with them.
