### ISSUE TITLE
Tag 0.4.2 doesn't build with bazel 0.10.x

### ISSUE THREAD

**Issue by therealmik** [bazelbuild/rules_closure#254]
There's an incorrect _check_bazel_version in the 0.4.2 tag (it compares a tuple of strings), so anyone including the rules_closure repo is broken.

This has been removed in the 0.4 branch, so maybe just release a new version?

**Comment by promiseofcake** [comment]
If we also wanted to re-implement that check `bazel-skylib` is now the idiomatic way of doing that:
https://github.com/bazelbuild/bazel-skylib/blob/master/lib/versions.bzl

example:
```
http_archive(
    name = "bazel_skylib",
    strip_prefix = "bazel-skylib-ff23a62c57d2912c3073a69c12f42c3d6e58a957",
    url = "https://github.com/bazelbuild/bazel-skylib/archive/ff23a62c57d2912c3073a69c12f42c3d6e58a957.tar.gz",
)

load("@bazel_skylib//:lib.bzl", "versions")

versions.check(minimum_bazel_version = "0.8.1")
```

**Comment by jorgedavila25** [comment]
Any updates on this?

**Comment by EduCampi** [comment]
Hello,
This issue makes bazel unusable for closure.
Is there any workaround?
Is it possible to download this repo, modify it and call it locally?

Thanks!

**Comment by promiseofcake** [comment]
@EduCampi if you use HEAD it should be okay at this point until a new release is cut.

**Comment by pawelz** [comment]
Yes, HEAD works. When are you planning to cut a new release? It's a bit sad there is no usable released version.
