### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/rules_closure#272]
Bazel is planning to move away from native rules for external repositories to
Skylark rules, mainly because bundling every version control system in bazel
does not scale. As part of this effort, we plan to submit
https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause
bazel by default to insist that the skylark versions the git and http rules for
external repositories be used. This can be disabled by a flag for at least the
next 6 months, but we still would appreciate if you could adopt your repository
to use the Skylark versions of those rules soon.

In fact, pull request #270 already achieves this transition.

A test run of downstream projects with that flag flip in bazel enabled can
be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

**Comment by jart** [comment]
Why support O(n) version control systems when you can support O(0)?

Every version control system, to the best of my knowledge, makes tarballs available that can be obtained via HTTP. I've recommended `git_repository` be removed for years. 

Would the Bazel team consider removing native `http_archive` from the docs? Deprecating and deleting it is going to cause pain and break history. Just sweep it under the rug and pretend it never happened. I worked on the code. Surely it can't be too problematic to maintain.

As for the Skylark replacement, consider having patch functionality native to Bazel. I'm not entirely sure `utils.bzl` will work on Windows.

Also I recommend having things like `licenses`, `testonly_`, `tags` etc. attributes on the new Skylark replacement. The `url` attribute was soft-deprecated when `urls` was introduced and that doesn't need to be carried over, if it can be avoided. 

Please also take into consideration that, changes to `@bazel_tools//...` can't be pinned. Making breaking changes to Skylark rules that are accessed this way, will break historical of the repositories that reference them in this manner.

**Comment by jart** [comment]
Also, has the Bazel team had time to embed a POSIX ToyBox user-space with the Bash shell? The GNU patch program is kind of tiny, about 500kB when compiled with `-Os` IIRC. If you bundled a POSIX compliant system into Bazel then I'd feel a lot more comfortable with the technical direction being suggested here, of moving away from native functionality, since that means we're losing all the portability and homogeneity benefits the Java language provides. It might also necessary to have triple quoted strings so we can write POSIX shell scripts in our Skylark files.

**Comment by dslomov** [comment]
As far as I am aware, this repository (rules_closure) does not make use of any features that you claim are not supported in the Skylark http_archive, therefore there is no reason to block this change from rules_closure perspective. 

Also, `@bazel_tools` is as "pinned" as Bazel itself (it is a part of Bazel) so there is no difference in this regard. 

If you have any concerns with removal of native http_archive, please raise them on Bazel issue tracker.
