### ISSUE TITLE
Java 9: Please upgrade outdated Dagger version

### ISSUE THREAD

**Issue by davido** [bazelbuild/rules_closure#275]
This project prevents Gerrit Code Review to be built with java 9. Dagger version is too old 
and doesn't support Java 9: [1].

Dagger 2.14.1 is known to supprot Java 9. The upgrade was already done in this PR: [2]. Unfortunately, the review was staled.

* [1] http://paste.openstack.org/show/724001
* [2] https://github.com/bazelbuild/rules_closure/pull/235/commits/a2cd36de988de02efc813b54af8290bbf5ffe6a9

**Comment by regisd** [comment]
> io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/compiler/BUILD:17:1: Compiling Java headers external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/compiler/libcompiler-hjar.jar (1 files) and running annotation processors (ComponentProcessor) failed (Exit 1)
> java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated
> 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
> 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
> 	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
> 	at com.google.devtools.build.java.turbine.javac.JavacTurbineCompiler.compile(JavacTurbineCompiler.java:100)

**Comment by davido** [comment]
Actually this was already fixed in: [1].

[1] https://github.com/bazelbuild/rules_closure/pull/276
