### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_closure#311]
I'd like to be able to build rules_closure with `--all_incompatible_changes`:
  `cd rules_closure && bazel build --all_incompatible_changes //...`

It may not be possible to fix every issue now due to transitive dependencies, but we should try to fix the issues from this repository.

**Comment by davido** [comment]
Right, after applying your fixes, linked to this issues, I'm getting protobuf issues:

```
$ bazel build //...
INFO: Invocation ID: f2c43e6d-2a31-4c5a-bffc-70ec037113cb
INFO: Build options have changed, discarding analysis cache.
Analyzing: 1306 targets (181 packages loaded, 95 targets configured)
    Fetching @libfontconfig_amd64_deb; fetching
    Fetching @clang; fetching
ERROR: build interrupted
INFO: Elapsed time: 2.249s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (182 packages loaded, 112 targets configured)
    currently loading: @local_jdk//
    Fetching @clang; fetching
    Fetching @com_google_template_soy; fetching
davido@wizball:~/projects/rules_closure (master *%>)$ bazel build  --all_incompatible_changes closure/testing/externs:phantomjs 
INFO: Invocation ID: ae38d14c-23fa-4a61-ab9c-e808acb55599
INFO: Build options have changed, discarding analysis cache.
ERROR: /home/davido/.cache/bazel/_bazel_davido/81f5d7d2ef89f86f4b7d8c7ea37200c2/external/com_google_protobuf/protobuf.bzl:127:19: Traceback (most recent call last):
	File "/home/davido/.cache/bazel/_bazel_davido/81f5d7d2ef89f86f4b7d8c7ea37200c2/external/com_google_protobuf/protobuf.bzl", line 122
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/home/davido/.cache/bazel/_bazel_davido/81f5d7d2ef89f86f4b7d8c7ea37200c2/external/com_google_protobuf/protobuf.bzl", line 127, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params to temporarily disable this check.
ERROR: /home/davido/projects/rules_closure/java/io/bazel/rules/closure/worker/BUILD:17:1: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors and referenced by '//java/io/bazel/rules/closure/worker:worker'
ERROR: Analysis of target '//closure/testing/externs:phantomjs' failed; build aborted: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 0.415s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (25 packages loaded, 73 targets configured)
    currently loading: @com_google_protobuf//
    Fetching @remotejdk10_linux; Restarting.
```

It seems that those issue were fixed upstream, so that rules_closure could benefit from bumping protobuf version.

**Comment by jart** [comment]
Why? Is the issue stuff like https://github.com/bazelbuild/bazel/issues/6461? Because no one cares about the mechanics of `+` vs. `dict` in a fringe language. These sorts of engineering practices are completely unacceptable. You can't make decisions unilaterally that destroy user data, due to personal opinions on style.

**Comment by laurentlb** [comment]
Remaining issues:
* `--incompatible_depset_is_not_iterable`
* `--incompatible_depset_union`
* `--incompatible_disable_deprecated_attr_params`

**Comment by davido** [comment]
@laurentlb Any progress here? Now, that the Protobuf upgrade to 3.7.0 is in progress: https://github.com/bazelbuild/rules_closure/pull/342 these are the only incompatible issues remained.

**Comment by davido** [comment]
@jart You are a brilliant software engineer. Your recent comments in this and other projects are inappropriate. Open source project is not a debate club, but someone has to do tough decisions.

We could and should make our point whether we agree or disagree, but once the decisions are made we should just accept them.

**Comment by sgammon** [comment]
@davido I don't understand why @jart's comment upset you. I find myself agreeing with the points she makes here. Just my 2 cents as a user of the actual library.
