### ISSUE TITLE
closure_js_test does not allow multiple entry_points

### ISSUE THREAD

**Issue by marcbaechinger** [bazelbuild/rules_closure#323]
When running a closure_js_test rule an entry point needs to be provided to not have the compiler remove all code. 

I have a couple of tests which are goog.modules with different module names. The closure_js_test currently only allows a single entry point. When adding more than a single entry point the test fails.

So currently there needs to be a closure_js_test rule for each test with a different module name.

**Comment by michaelfig** [comment]
Is there any proposed solution, or do I need to make a meta-rule to assign individual entry points for each test?
