### ISSUE TITLE
zip inputs ignored by closure_js_deps

### ISSUE THREAD

**Issue by ribrdb** [bazelbuild/rules_closure#324]
@gkdn added zip file support in commit in #298 
However it doesn't work with closure_js_deps.
If I create a j2cl_library and include it in the deps of closure_js_deps, the output deps.js file includes reference to the java classes, but the java classes don't get listed as sources.
Then when you try to run the code it says: 
  Uncaught Error: Bad dependency path or symbol: com.example.FooBar
  at com_google_javascript_closure_library/closure/goog/base.js:2795:11
  
  Error: Bad dependency path or symbol: com.example.FooBar
      at visit (com_google_javascript_closure_library/closure/goog/base.js:2795:17)
      at visit (com_google_javascript_closure_library/closure/goog/base.js:2807:13)
      at visit (com_google_javascript_closure_library/closure/goog/base.js:2807:13)
      at visit (com_google_javascript_closure_library/closure/goog/base.js:2807:13)
      at goog.DebugLoader_.load_ (com_google_javascript_closure_library/closure/goog/base.js:2814:7)
      at Object.goog.require (com_google_javascript_closure_library/closure/goog/base.js:845:27)

**Comment by ribrdb** [comment]
I just realized another issue with this. To run without compilation we need the .js files in runfiles. That's not possible unless we at least know which js files are in the zip

**Comment by gkdn** [comment]
Hi Ryan.
If this is in the context of J2CL; the recommend way to run without compilation is still to bundle JavaScript files; otherwise it will be slow to load them individually would need updates on the serving infra.

**Comment by ribrdb** [comment]
Yes, I'm trying to use j2cl. All our tests and it development servers are implemented using closure_js_deps.
I just tried using the bundle compilation mode like j2cl_application uses. I was able to get things working that way, but I can't get sourcemaps to work. The bundle seems to ignore output_wrapper. Instead the browser picks up the sourcemaps for the last file in the bundle. I do see a sourcemap generated for the bundle, but even if I manually edit the source file to reference it I don't get any source in chrome.

**Comment by gkdn** [comment]
I didn't have opportunity to go over sourcemap use case for open source but I remember that is was missing some stuff even for our sample helloworld setup.
I need to take a deeper look to find all missing pieces but for example one needs to be able to serve requests for the Java source in the zip files. Being said that, J2CL generated code is not hard to debug after you get used to though it would be good to make sourcemaps working.

wrt. js_deps and original request; it is generally not considered a good practice and most people are moving away from it but if you really want to make it work with zip files you can do that. But I still recommend you to switching to bundling for the long run.

**Comment by gkdn** [comment]
closure_js_deps is removed, closing the bug.
