### ISSUE TITLE
Disable the inclusion of transitive sources

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#335]
How do you recommend including a `closure_js_binary` without including all of its transitive sources in the deployable artifact? 

In particular, I have a setup like this:

```
closure_js_binary(
    name = "async_bin",
    compilation_level = "ADVANCED",
    ... 
)

go_library(
    name = "go_default_library",
    srcs = [
    ...
    ],
    data = [
        ":async_bin",
    ],
)

go_binary(name = "bin", deps = [":go_default_library"], ... )

pkg_tar(srcs = [":bin"], include_runfiles=True, ...)
```

The resulting .tar file ends up with all transitive js sources, when I would prefer it gets only the compiled output.

**Comment by gkdn** [comment]
You can just use ```:async_bin.js``` which is the compiled output.

**Comment by robfig** [comment]
Ah, so simple. Thank you
