### ISSUE TITLE
closure_template_java_library not building

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#34]
Hi,

I was hoping to get advice on the recommended way to get my closure_template_java_library target to build. It looks like it hard codes in an expectation that Guava is in my source tree, but maybe I'm missing something.

I'm using the code in this repo:
https://github.com/robfig/undertow-bazel-closure-tools

WORKSPACE

```
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()

maven_jar(
    name = "com_google_guava_guava",
    artifact = "com.google.guava:guava:19.0",
)
```

BUILD

```
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_template_java_library")

closure_template_java_library(
    name = "coffeerun_soy_java",
    srcs = ["templates/index.soy"], 
    java_package = "com.robfig",
    deps = [
        ":com_google_guava_guava",
    ],
)

java_library(
    name = "com_google_guava_guava",
    visibility = ["//visibility:public"],
    exports = [
        "@com_google_guava_guava//jar",
    ],
)
```

ERROR
```
$ ~/bazel/output/bazel build :coffeerun_soy_java
.........
ERROR: /Users/robfig/closure-tools-server/BUILD:60:1: no such package 'java/com/google/common/collect': BUILD file not found on package path and referenced by '//:coffeerun_soy_java'.
```

Thanks!
Rob

**Comment by robfig** [comment]
Tried with latest closure_rules, and now I get a different error:

```
./bazel/output/bazel build :coffeerun_soy_java
INFO: Found 1 target...
ERROR: /Users/robfig/undertow-bazel-closure-tools/BUILD:72:1: Generating SOY v2 Java files //:coffeerun_soy_java_files failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
errors during Soy compilation
In file bazel-out/local-fastbuild/bin/libcom_google_guava_guava.jar:1:1: parse error at 'PK': expected eof, {alias, {namespace, {delpackage, {deltemplate, or {template
PK
^

Target //:coffeerun_soy_java failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.425s, Critical Path: 1.16s
```

**Comment by robfig** [comment]
Never mind! It works after I removed guava from the deps. Everything's great. Thanks!

**Comment by jart** [comment]
That's an odd error. I wish I knew more about why that happened. It doesn't seem like adding Guava to deps should do that.

By the way, I never got around to writing tests for `closure_template_java_library`. Would you be interested in contributing a pull request adding an example invocation to [closure/templates/test/BUILD](https://github.com/bazelbuild/rules_closure/blob/master/closure/templates/test/BUILD)? Our test runner basically just says `bazel build //closure/...` and `bazel test //closure/...`.

**Comment by jart** [comment]
Oh one more thing. When you run `closure_repositories()` it already adds Guava to your project, under the name `guava`. So you can just reference that. Or you can say `closure_repositories(omit_guava=True)` to override the version.

**Comment by robfig** [comment]
Sure.. what do you envision the test case being? A build rule plus a rule comparing the result against a golden java file checked in?

Thanks for noting the guava being unnecessary. Removed from my repo.

**Comment by jart** [comment]
At the very least, it would be nice to have the build rule itself, so we'll know if it has a hard failure. A golden for the entire output might be overkill. It might be better to use `file_test`'s `regexp` attribute (in this repository) to make sure at least some substring is in there.
