### ISSUE TITLE
closure_js_binary/library: "main", "css", "depmode" parameter issues

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#35]
The README should include documentation for the closure_js_binary parameter called "main"

**Comment by jart** [comment]
Thanks for noticing this. I'll add it later this week.

**Comment by robfig** [comment]
Cool! Conversely, it looks like closure_js_library does not accept the "depmode" parameter, and closure_js_binary does not accept the "css" parameter.

```
ERROR: /Users/robfig/undertow-bazel-closure-tools/BUILD:30:1: //:coffeerun_bin: no such attribute 'css' in 'closure_js_binary' rule.
ERROR: /Users/robfig/undertow-bazel-closure-tools/BUILD:41:1: //:coffeerun_lib: no such attribute 'depmode' in 'closure_js_library' rule.
```
