### ISSUE TITLE
phantomjs leaks out of the sandbox

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/rules_closure#351]
When I run tests on Debian Buster, I get the following failure:

```
140302110000960:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140302110000960:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140302110000960:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140302110000960:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
```

From some targeted stracing, I'm seeing that the phantomjs binary is reading /etc/ssl/openssl.cnf.  Buster upgrades openssl far enough that the config in /etc/ is too different and won't work.  The correct fix is to provide an openssl.cfg with phantomjs that works.

This is blocking a debian upgrade for us, so I'll likely dig in and try to provide a fix.

**Comment by impalanichamy** [comment]
got this error when chack the version of phantomjs in my debian system

Auto configuration failed
139888421578688:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
139888421578688:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
139888421578688:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
139888421578688:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf

**Comment by saikumar-everest** [comment]
Any solution to this yet?

**Comment by AustinSchuh** [comment]
My fixes were submitted in 2019.  It was enough for me to operate on Debian Buster where I couldn't before.

**Comment by tobia** [comment]
Even quicker version of the harky workaround:
```export OPENSSL_CONF=/dev/null```

**Comment by JorgeLNH** [comment]
Thanks **tobia**, it worked.

**Comment by kcs-santoshahire** [comment]
I was also facing same issue,

Thanks @tobia its working..!

**Comment by meiremans** [comment]
> 

thanks @tobia

adding ENV OPENSSL_CONF=/dev/null to a Dockerfile based on node:16 will make phantomjs work again.

**Comment by karthikeyaGit61** [comment]
This worked for @tobia

**Comment by dbauszus-glx** [comment]
I was able to solve this by installing openssl 3.0.3 from source and switch to node v18+

The problem occured for me when I upgraded from Ubuntu 21.10 to 22.04

**Comment by 62015021** [comment]
Error: html-pdf: Unknown Error
Auto configuration failed

    at ChildProcess.respond (/home/chayanin/sale-invoice-a4/node_modules/html-pdf/lib/pdf.js:134:17)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
Error: html-pdf: Unknown Error
Auto configuration failed


me run in server help plz

**Comment by wyvern800** [comment]
> export OPENSSL_CONF=/dev/null This is working but is not a permanent solution. I am getting this again and again after closing the terminal. Is there any permanent solutions? @tobia

Thank you so much!, saved me and my co-workers life, really worked here at the company I work lol!

**Comment by 42510SR** [comment]
i tried this export OPENSSL_CONF=/dev/null  but it didnt worked , what is the issue like why i am getting this "Error: html-pdf: Received the exit code '1'\nhtml-pdf: Evaluation - ReferenceError: Can't find variable: $\nStack:\n  at undefined\n"
