### ISSUE TITLE
closure_js_template_library.should_provide_require_soy_namespaces does nothing

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#381]
I'm using `closure_js_template_library` with an application that uses closure modules, so I need the generated code to use `goog.provide` / `goog.require`.  The documentation says that `should_provide_require_soy_namespaces` is passed through to the compiler, but in fact it does nothing because SoyToJsSrcCompiler had that flag removed at some point. 

That sounds ok, except I'm overriding it with a version of Soy that is a year or two old, and I can't update without fixing the various backwards incompatibilities that were introduced since then. The compiler I'm using still has that flag, and it defaults to false, so it's not possible for me to proceed without making some sort of change.

I wanted to ask if you would be open to a generic `args` parameter that acts as a passthrough to the compiler? This would solve this case as well as possible future cases when the flags change. There are also a good number of flags, so it's not infeasible to think that there are other valid use cases for wanting to get at them. 

Either way, I think it's worth updating the documentation on this parameter or possibly removing it entirely. I can do that if you give me a green light to make the pull request described above.

Thanks

https://github.com/bazelbuild/rules_closure#closure_js_template_library

**Comment by gkdn** [comment]
The documentation should be removed.
w.r.t passthrough; we can accept something in the lines of defs attribute for closure_js_binary rule.

**Comment by robfig** [comment]
I also removed the old `should_provide_require_soy_namespaces` property to reduce confusion in the future. Let me know if you'd like to leave it with a note instead.
