### ISSUE TITLE
Closure Library targets omit third_party tree

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#382]
Some code that I'm trying to build with rules_closure requires `goog.dom.query`, which is provided by this file, within the closure_library jar: `third_party/closure/goog/dojo/dom/query.js`. The `third_party` tree does not seem to be covered in the auto-generated BUILD rules provided by rules_closure. It seems like the script that generates them (`closure/library/regenerate.py`) could probably easily cover these too, although it's not clear exactly how the directory structure should work; I guess it could be generated in //closure/library/third_party despite the fact it doesn't quite line up with the placement. 

Thoughts?

**Comment by gkdn** [comment]
I'm not much familiar with this part but seems like it is already available here:
https://github.com/bazelbuild/rules_closure/blob/master/third_party/closure/library/dojo/dom/BUILD

**Comment by robfig** [comment]
!! 
Sorry about that, not sure how I missed it! Thank you
