### ISSUE TITLE
pedantic mode option to make deprecated & unnecessaryCasts errors

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#39]
This is more of a question than an issue but I couldn't find a mailing list. What is the best forum for end user discussion about the bazel rules_closure?

When setting pedantic mode, deprecated and unnecessaryCasts are only warnings (not errors).

    JS_PEDANTIC_ARGS = [
        "--jscomp_error=*",
        "--jscomp_warning=deprecated",
        "--jscomp_warning=unnecessaryCasts",
    ]

This can be overcome by passing flags directly to the compiler in the BUILD file, for example:

    defs = [
      "--jscomp_error=deprecated",
      "--jscomp_error=unnecessaryCasts",
    ],

I would expect pedantic mode to make all diagnostic groups errors. Is the best way to override the default pedantic behavior by using defs (as above)? Am I missing a better configuration hook?

**Comment by jart** [comment]
1. I'll create a mailing list later today or tomorrow. I've been meaning to do that.

2. The best option at the moment is to use `defs`. I've been intentionally avoiding creating thin wrappers for command line flags, unless my abstraction can provide additional value.
