### ISSUE TITLE
Use of `strip_import_prefix` with `closure_proto_library`

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/rules_closure#390]
[During discussion](https://github.com/bazelbuild/rules_closure/issues/388#issuecomment-499995862_) under #388, @Yannic suggested an issue be filed to enable support for `strip_import_prefix` in the `closure_proto_library` rule.

We have a tree of protos, defined via `proto_library`. When we try to create accompanying rules for these protos via `closure_proto_library`, Bazel fails to build them, with the following output:

```
ERROR: /private/var/tmp/_bazel_sam/.../external/schema/vendor/google/bq/BUILD.bazel:16:1: Generating JavaScript Protocol Buffer bq failed (Exit 1): protoc failed: error executing command 
  (cd /private/var/tmp/_bazel_sam/.../execroot/SomeWorkspace && \
  exec env - \
  bazel-out/host/bin/external/com_google_protobuf/protoc -Ibazel-out/darwin-fastbuild/genfiles/external/schema -Ibazel-out/darwin-fastbuild/genfiles/external/com_google_protobuf '--js_out=import_style=closure,library=bq,add_require_for_enums:bazel-out/darwin-fastbuild/bin/external/schema/vendor/google/bq')
Execution platform: @bazel_tools//platforms:host_platform
Missing input file.
INFO: Elapsed time: 74.141s, Critical Path: 15.87s
INFO: 239 processes: 229 local, 10 worker.
FAILED: Build did NOT complete successfully
```

@gkdn, @Yannic asked that I tag you and ask that you assign this to him.

**Comment by Yannic** [comment]
Thanks, I'll look into it.

@stanley-cheung FYI, This issue should also exist in gRPC-Web.
