### ISSUE TITLE
closure_js_binary: output_wrapper for adding sourceMappingURL

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#399]
With plovr, we had been using output_wrapper to add the sourcemap URL to compiled binaries:

```
  "output-wrapper": "(function(){%output%})();\n//# sourceMappingURL=/sourcemap?id=users_dev\n"
```

When I try the same thing with `closure_js_binary`:
```
closure_js_binary(
    name = "users_dev",
    compilation_level = "SIMPLE",
    language = "ECMASCRIPT5",
    output_wrapper = "(function(){%output%})();\n//# sourceMappingURL=/sourcemap?id=users",
```

I get an error: 
```
java.lang.IllegalArgumentException: a source must have a name
```

I believe this is due because the output_wrapper is not properly quoted in the command line that gets built up. If I try to quote it myself by adding a single quote to the beginning and end:
```
    output_wrapper = "'(function(){%output%})();\n//# sourceMappingURL=/sourcemap?id=users'",
```

I get a different error:
```
java.lang.RuntimeException: Cannot read code of a source map's source file.
Caused by: java.nio.file.NoSuchFileException: /# sourceMappingURL=/s/users/public/js/users.js.map'
```

If I escape the \n, then I end up with a literal \n in the JS file.

Should I look at submitting a pull request + fix for this? How do others add the sourcemap URL to the end of the file?

**Comment by robfig** [comment]
Would you be open to adding a `sourceMappingURL` attr to closure_js_binary, which if specified would have the effect of adding that last line to the file?

**Comment by Yannic** [comment]
`output_wrapper` is powered by [--output_wrapper](https://github.com/google/closure-compiler/blob/445fdf3f31d848d955d71d10f4794b45c0f4d1a6/src/com/google/javascript/jscomp/CommandLineRunner.java#L349), which doesn't seem to allow multi-line wrappers. We should be able to manifest the wrapper as file and switch to `--output_wrapper_file`.
