### ISSUE TITLE
closure_js_binary - Internal error - "Too many template parameters" 

### ISSUE THREAD

**Issue by robfig** [bazelbuild/rules_closure#404]
I'm getting an internal error when building a sizable `closure_js_binary` target. Do you have any advice on how to diagnose this, or have you seen such a thing before? I'm not doing anything exotic or unusual, certainly nothing with jsdoc template parameters.

```
$ bazel build src/com/corp/consumerfeedback/consumerfeedbackstorm/public/js:consumerfeedbackstorm  
ERROR: /Users/robfig/alpha/src/com/corp/consumerfeedback/consumerfeedbackstorm/public/js/BUILD:4:1: Compiling 297 JavaScript files to src/com/corp/consumerfeedback/consumerfeedbackstorm/public/js/consumerfeedbackstorm.js failed (Exit 1): ClosureWorker failed: error executing command
  (cd /private/var/tmp/_bazel_robfig/1db08896ecff7e5e96a745981c3b77e6/execroot/corp && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/ClosureWorker @@bazel-out/darwin-fastbuild/bin/src/com/corp/consumerfeedback/consumerfeedbackstorm/public/js/consumerfeedbackstorm.js-0.params)
Execution platform: @bazel_tools//platforms:host_platform
[internal]:21: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:25: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:28: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:28: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:35: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:40: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:51: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:55: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:350: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

[internal]:351: ERROR - Too many template parameters
  Codes: JSC_TOO_MANY_TEMPLATE_PARAMS, tooManyTypeParams

10 error(s), 0 warning(s), 88.2% typed
```

**Comment by sgammon** [comment]
Could you post a snippet from your templates at all? I’m just curious about the syntax causing this

**Comment by robfig** [comment]
Assuming that "templates" in the message refers to [generic types](https://github.com/google/closure-compiler/wiki/Generic-Types), I have none in my codebase. A git grep '@template' returns no hits, except for the jquery-1.9 externs ($.grep). Generally, we have not done much in the way of annotating for closure compiler. I have another significant js binary building without a problem from the same codebase, but it's possible this is the first one that makes use of $.grep? 

On that topic, since we've been developing without these checks for a while, I do have a lot of suppressions on the various libraries. If there are any suppressions in particular that might be masking this problem, I can try dropping them, but that seems probably unrelated. 

Lastly, not to grasp at straws, but this does remind me of a question I got 6 months ago when someone was trying to upgrade the version of Closure Compiler used with plovr. 

```
externs.zip//es6.js:1223: ERROR - The type function(?): undefined cannot be templatized
 *     cond(isUnknown(VALUE), unknown(),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

which was triggered by this template:
```
/**
 * @param {?(function(this:void, TYPE):VALUE)=} opt_onFulfilled
 * @param {?(function(this:void, *): *)=} opt_onRejected
 * @return {RESULT}
 * @template VALUE
 * @template RESULT := type('Promise',
 *     cond(isUnknown(VALUE), unknown(),
 *       mapunion(VALUE, (V) =>
 *         cond(isTemplatized(V) && sub(rawTypeOf(V), 'IThenable'),
 *           templateTypeOf(V, 0),
 *           cond(sub(V, 'Thenable'),
 *              unknown(),
 *              V)))))
 * =:
 * @override
 */
Promise.prototype.then = function(opt_onFulfilled, opt_onRejected) {};
```

It's not exactly the same error message, but "issue with template" seems similar in concept. Shrug. 

I realize it's tough to diagnose when I can't share the source code, so thanks for your time!

**Comment by robfig** [comment]
This seems to be specific to rules_closure. 

I downloaded the latest closure-compiler, and I successfully compiled using the same flagfile as is generated by for rules_closure, after deleting the unsupported flags (`JsCompiler, `--output_errors`, `--info`, `--sourcemap_location_mapping [synthetic`). 

```
java -jar ~/Downloads/compiler-latest/closure-compiler-v20190618.jar --flagfile bazel-out/.../appjs-0.params
```

Presently the version of closure compiler used by rules_closure is 20190528. I checked that out, built it, and found that version worked as well. 

Any ideas?

**Comment by robfig** [comment]
Well, as suggested by the error message, adding this property to closure_js_binary fixes it:
```
  suppress_on_all_sources_in_transitive_closure = ["tooManyTypeParams"],
```

so it's probably not worth the effort of figuring out why the error message is unhelpful or where the error is coming from. Closing
