### ISSUE TITLE
Replace JSChecker with Java version that plugs into compiler

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#41]
The current linter rule (closure_js_lint_test) uses the deprecated python closure-linter instead of the the new linter.jar (which is open sourced in the closure-compiler repository). The new linter has better support for ES6.

Can closure_js_lint_test be upgraded to use the new linter?

**Comment by jart** [comment]
This isn't actually going to be able to lint Closure Style due to a bug google/closure-compiler/pull/1768. This linter also doesn't check things like how two blank lines need to be before members, and three blank lines need to be before constructors. So I don't think it's really a replacement for the Python linter quite yet.

However this would be REALLY GOOD for incrementally checking the syntax of JavaScript code. So I'm repurposing this bug.

**Comment by hochhaus** [comment]
@jart Thanks.

I was under the impression from the following resources that linter.jar/clang-format was the new best practice internally at Google.
  * closure-library moving off python linter https://github.com/google/closure-library/commit/5b57754bbc59d66a98a939804cf91d85094e0a9a
  * python closure-linter mentioning intent to deprecate https://github.com/google/closure-linter/issues/98
  * John Lenz [comments](https://groups.google.com/d/msg/closure-compiler-discuss/KrWtaKItdog/6yYeMCHlAQAJ) on closure-compiler-discuss

Am I moving too quickly in assuming that gjslint is deprecated / is in the process of being deprecated? To the best of your knowledge, do any plans exist to update gjslint with support for ES6? Should new code be written per the formatting guidelines of gjslint or linter.jar/clang-format?

Would clang-format (in addition to linter.jar) address your concerns about blank lines before members/constructors?

**Comment by jart** [comment]
I don't know what's up with linter.jar but there's other stuff I'm already doing like [jschecker.py](https://github.com/bazelbuild/rules_closure/blob/master/closure/compiler/jschecker/jschecker.py). So I'm thinking we shouldn't use linter.jar. We could just write our Java program that plugs directly in the Closure Compiler, does the linting, validation, strict dependency checking, and all that good stuff. What do you think?

**Comment by hochhaus** [comment]
@jart Thanks, that sounds good to me.
