### ISSUE TITLE
Updating Closure jar on Bazel mirror

### ISSUE THREAD

**Issue by psybuzz** [bazelbuild/rules_closure#456]
Hello, I see that a Closure .jar is unavailable on the Bazel mirror [1], but 200s on the Maven URL [2].

Is there some process needed to update the Bazel mirror?

[1]
https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20190909/closure-compiler-unshaded-v20190909.jar

[2]
https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20190909/closure-compiler-unshaded-v20190909.jar

**Comment by alexeagle** [comment]
I mirrored this file just now, thanks for reporting it.

Of course this bug will recur with the next closure-compiler release unless we add bazel mirroring to the release steps. I'll reach out to someone on that team.

**Comment by psybuzz** [comment]
Thank you!

**Comment by nicolasgarnier** [comment]
We'd also need this file mirrored: https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20180805/closure-compiler-unshaded-v20180805.jar

It's breaking the build from our project https://github.com/googlecodelabs/tools

**Comment by nicolasgarnier** [comment]
nm I'll open another issue to get more visibility.

**Comment by nicolasgarnier** [comment]
Filed here https://github.com/bazelbuild/rules_closure/issues/472
