### ISSUE TITLE
Missing Closure jar on bazel mirror

### ISSUE THREAD

**Issue by nicolasgarnier** [bazelbuild/rules_closure#472]
We need this file mirrored: https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20180805/closure-compiler-unshaded-v20180805.jar

The file is available onrepo1.maven.org and was served by the bazel mirror up until recently.
It's breaking the build from our project https://github.com/googlecodelabs/tools

**Comment by gkdn** [comment]
@nicolasgarnier Is there a reason to use a old version of the compiler?

@philwo This is about mirroring of an old release of the JS compiler; not directly related to rules_closure. Where is this bug should be filed?

**Comment by nicolasgarnier** [comment]
Old project still using Bazel 0.18.1 with not much resources assigned to do the upgrade :)

**Comment by davido** [comment]
@gkdn @jDramaix @Yannic 

We (Gerrit Code Review) are seeing supious warning during the build and CI related to stale URL in closure/repositories.bzl file:

```
j706430@defender:~$ wget https://mirror.bazel.build/github.com/google/protobuf/archive/v3.11.4.tar.gz
--2020-04-21 13:31:49--  https://mirror.bazel.build/github.com/google/protobuf/archive/v3.11.4.tar.gz
2020-04-21 13:31:49 ERROR 404: Not Found.

j706430@defender:~$ wget https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200112/closure-compiler-unshaded-v20200112.jar
--2020-04-21 13:32:29--  https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200112/closure-compiler-unshaded-v20200112.jar
2020-04-21 13:32:29 ERROR 404: Not Found.

j706430@defender:~$ wget https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200406/closure-compiler-unshaded-v20200406.jar
--2020-04-21 13:34:42--  https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200406/closure-compiler-unshaded-v20200406.jar
2020-04-21 13:34:42 ERROR 404: Not Found.

```

**Comment by Yannic** [comment]
Looks like these were never uploaded to bazel mirror.

@meteorcloudy Can you please upload these files to bazel mirror?
  - `https://github.com/google/protobuf/archive/v3.11.4.tar.gz`
  - `https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200112/closure-compiler-unshaded-v20200112.jar`
  - `https://repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200406/closure-compiler-unshaded-v20200406.jar`

**Comment by davido** [comment]
@Yannic but could @meteorcloudy upload anything to Maven Central? There is very complex release tool chain machinery to upload any artifact there? If artifact is only published on bazel mirror, then we have to remove th Maven Central URL entirely.

**Comment by Yannic** [comment]
Yes, I was asking to get the artifacts uploaded to bazel mirror.

I may be missing something, but your comment seems to be about missing files on bazel mirror. If we add them to the mirror, this should be fixed (IMO, it's always a good idea to have multiple URLs, just in case bazel mirror ever shows hick-ups ;) ).

**Comment by davido** [comment]
> I may be missing something, but your comment seems to be about missing files on bazel mirror.

You are right. I wasn confused with "repo1.maven.org" substring in the URL but is all about bazel mirror.

**Comment by meteorcloudy** [comment]
OK, the following artifacts are now available:

- https://mirror.bazel.build/github.com/google/protobuf/archive/v3.11.4.tar.gz
- https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200112/closure-compiler-unshaded-v20200112.jar
- https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200406/closure-compiler-unshaded-v20200406.jar
- https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20180805/closure-compiler-unshaded-v20180805.jar
- https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20180805/closure-compiler-unshaded-v20180805.jar

**Comment by jDramaix** [comment]
We are really interested to upload our other project artifacts on bazel mirror too. Is there any documentation or process to follow for doing that ?

**Comment by meteorcloudy** [comment]
This currently can only be done by a Bazel developer at google. Can you open an issue in bazel repo and ping me?

**Comment by davido** [comment]
@meteorcloudy Thanks for the quick fix, really appreciated!
