### ISSUE TITLE
Missing multiple recent `rules_closure` archives in Bazel mirror

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#495]
The [Setup section in the `README`][readme-setup] says to add the following code snippet in `WORKSPACE`:

```bzl
http_archive(
    # ...snip...
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
    ],
)
```

However, the first URL (https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz) returns a 404.

Additionally, the following releases **don't exist** on the mirror, either:

* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.9.0.tar.gz
* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.8.0.tar.gz

These releases **do exist** on the mirror, however:

* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.7.0.tar.gz
* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.6.1.tar.gz
* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.6.0.tar.gz
* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.4.2.tar.gz
* https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.4.1.tar.gz
* _note: I didn't check any older releases_

which suggests that these releases used to be uploaded to the mirror in the past.

Can the missing releases be uploaded to the Bazel mirror, or should the code sample stop referring to the missing file?

[readme-setup]: https://github.com/bazelbuild/rules_closure/tree/62746bdd1087c1198a81143e7d8ef3d144a43c0f#setup

**Comment by Yannic** [comment]
Thanks for reporting! That was probably just an oversight.

@meteorcloudy Can you upload the following files to Bazel-mirror, please? Thank you!
  - `https://github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz`
  - `https://github.com/bazelbuild/rules_closure/archive/0.9.0.tar.gz`
  - `https://github.com/bazelbuild/rules_closure/archive/0.8.0.tar.gz`

**Comment by meteorcloudy** [comment]
https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.9.0.tar.gz
https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.8.0.tar.gz
Done.

**Comment by mbrukman** [comment]
Verified that they're all there; thanks for fixing!
