### ISSUE TITLE
Please create a new release past 0.10.0

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#497]
The latest release ([0.10.0](https://github.com/bazelbuild/rules_closure/releases/tag/0.10.0)) is from Oct 2019, which is quite old, and I've run into some issues with it, as mentioned in https://github.com/bazelbuild/rules_closure/issues/496, some of which have been fixed in the repo, so I am using an unnamed git commit hash instead of a release version.

Would it be possible to create a newer release with all the changes that have been made since 0.10.0 to make it easier for everyone to get the latest improvements and bug fixes?

Thanks!

**Comment by mbrukman** [comment]
While release 0.10.0 works locally on macOS, it [fails on Travis CI](https://travis-ci.org/github/mbrukman/preact-bazel-closure/jobs/722384357):

```
$ bazel build --config=ci //...
Extracting Bazel installation...
................
ERROR: /private/var/tmp/_bazel_travis/616ba4a0fc6920c1316870693f99fc06/external/io_bazel_rules_closure/closure/protobuf/closure_proto_library.bzl:66:21: name 'ProtoInfo' is not defined
ERROR: error loading package 'third_party/preact-without-babel': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
ERROR: error loading package 'third_party/preact-without-babel': Extension 'closure/protobuf/closure_proto_library.bzl' has errors
INFO: Elapsed time: 2.814s
The command "bazel build --config=ci //..." exited with 1.
```

Here's the `.bazelrc` used in that run:

```bzl
build:ci --noshow_progress --noshow_loading_progress --verbose_failures
```

And here's the `WORKSPACE` from that run:

```bzl
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "7d206c2383811f378a5ef03f4aacbcf5f47fd8650f6abbc3fa89f3a27dd8b176",
    strip_prefix = "rules_closure-0.10.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/0.10.0.tar.gz",
    ],
)

load("@io_bazel_rules_closure//closure:repositories.bzl", "rules_closure_dependencies", "rules_closure_toolchains")
rules_closure_dependencies()
rules_closure_toolchains()
```

---

**Comment by gkdn** [comment]
Added new release. 

(The issue you are seeing is related to bazel versions.)
