### ISSUE TITLE
Missing closure-compiler-unshaded-v20200614.jar on mirror.bazel.build

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#499]
PR https://github.com/bazelbuild/rules_closure/pull/489 (commit https://github.com/bazelbuild/rules_closure/commit/d69cb55fa6e4d2f627c017e9ad3088d70214e938) updated JsCompiler to v20200614:

https://github.com/bazelbuild/rules_closure/blob/d69cb55fa6e4d2f627c017e9ad3088d70214e938/closure/repositories.bzl#L656-L666

However, the JAR referenced above does not appear on the Bazel mirror, leading to the following warning when building:

> WARNING: Download from https://mirror.bazel.build/repo1.maven.org/maven2/com/google/javascript/closure-compiler-unshaded/v20200614/closure-compiler-unshaded-v20200614.jar failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

The file does exist on Maven, so the second entry in the list above succeeds and the build continues, but it would be nice to add this file to the Bazel mirror, and make it a part of the JsCompiler update process to avoid the error message in the future.

**Comment by gkdn** [comment]
It is removed now.
