### ISSUE TITLE
Please upload release 0.11.0 to the Bazel mirror

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#501]
@gkdn, thanks for creating release 0.11.0 as requested in https://github.com/bazelbuild/rules_closure/issues/497!

Unfortunately, this release isn't yet available on the Bazel mirror; opening https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.11.0.tar.gz shows the error:

> ```
> <Error>
> <Code>NoSuchKey</Code>
> <Message>The specified key does not exist.</Message>
> </Error>
> ```

The way the docs recommend using the releases is as follows

```bzl
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "d66deed38a0bb20581c15664f0ab62270af5940786855c7adc3087b27168b529",
    strip_prefix = "rules_closure-0.11.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.11.0.tar.gz",
        "https://github.com/bazelbuild/rules_closure/archive/0.11.0.tar.gz",
    ],
)
```

so while the build still works (because the GitHub URL is valid), Bazel shows an error about the Bazel mirror not providing the file it should be.

Thanks for your help!

**Comment by gkdn** [comment]
@philwo Could you pls add the latest release to Bazel mirror?

**Comment by philwo** [comment]
@gkdn Done!

**Comment by gkdn** [comment]
Tx
