### ISSUE TITLE
No way to suppress "JSC_INVALID_OCTAL_LITERAL"

### ISSUE THREAD

**Issue by eustas** [bazelbuild/rules_closure#502]
```
ProTip: "JSC_INVALID_OCTAL_LITERAL" or "es5Strict" or "es5StrictUncommon" can be added to the `suppress` attribute of:
  //:xxx
  Alternatively /** @suppress {es5Strict} */ can be added to the source file.
```
None of the proposed fixes work.

**Comment by eustas** [comment]
PING!

**Comment by gkdn** [comment]
If putting `/** @suppress {es5Strict} */` in your source didn't work, you need to file a bug with Closure compiler.

**Comment by eustas** [comment]
Compiler has parameter `--strict_mode_input` whose default value is `true`. I that is why compiler ignores the suppression.
If `--strict_mode_input` is set to false, then error does not appear.

**Comment by concavelenz** [comment]
Fixing the source might be the fastest way to resolve this.

**Comment by eustas** [comment]
Octal literals are 1.5-2x denser than hexadecimal for storing binary data (in strings).
"strict" more is useless anyways, so there is no real reason not to use octal literal for the purpose of library minification.
