### ISSUE TITLE
Missing soy-2020-08-24.jar artifact on https://mirror.bazel.build

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#505]
The `mirror.bazel.build` URL mentioned here:

https://github.com/bazelbuild/rules_closure/blob/c5a2d603d1b020c6fd3d7463e8e443c896d79f45/closure/repositories.bzl#L743-L750

namely:

https://mirror.bazel.build/repo1.maven.org/maven2/com/google/template/soy/2020-08-24/soy-2020-08-24.jar

does not exist (returns 404), while the Maven URL does:

https://repo1.maven.org/maven2/com/google/template/soy/2020-08-24/soy-2020-08-24.jar

---

Please upload the Soy artifact to the `mirror.bazel.build` server as well, or consider if it can be a transparent read-through cache that populates the file itself on first access if it doesn't exist there yet.

**Comment by gkdn** [comment]
It is removed now.
