### ISSUE TITLE
`goog.requireType` breaks //closure/library

### ISSUE THREAD

**Issue by sgammon** [bazelbuild/rules_closure#516]
In the switchover to `goog.requireType`, it seems like an issue is created with `rules_closure` w.r.t. `//closure/library`.

When I try to update `rules_closure` to the latest `closure-library` version, I get errors relating to `requireType` and missing dependencies, as expected:

```
external/com_google_javascript_closure_library/closure/goog/events/eventhandler.js:57: ERROR - Required namespace "goog.events.EventWrapper" never defined.
goog.requireType('goog.events.EventWrapper');
^
  ProTip: "JSC_MISSING_MODULE_OR_PROVIDE" or "missingSourcesWarnings" can be added to the `suppress` attribute of:
  @io_bazel_rules_closure//closure/library/events:eventhandler

external/com_google_javascript_closure_library/closure/goog/events/events.js:56: ERROR - Required namespace "goog.debug.ErrorHandler" never defined.
goog.requireType('goog.debug.ErrorHandler');
^
  ProTip: "JSC_MISSING_MODULE_OR_PROVIDE" or "missingSourcesWarnings" can be added to the `suppress` attribute of:
  @io_bazel_rules_closure//closure/library/events:events

external/com_google_javascript_closure_library/closure/goog/events/events.js:59: ERROR - Required namespace "goog.events.EventWrapper" never defined.
goog.requireType('goog.events.EventWrapper');
^
  ProTip: "JSC_MISSING_MODULE_OR_PROVIDE" or "missingSourcesWarnings" can be added to the `suppress` attribute of:
  @io_bazel_rules_closure//closure/library/events:events

3 error(s), 0 warning(s)

```

Now, this isn't entirely unexpected because the regex to calculate/generate dependencies for the Bazel side looks like:
```
REQUIRE_PATTERN = re.compile(
    r'^(?:(?:const|var) .* = )?goog\.require\([\'"]([^\'"]+)', re.M)
```

### Mitigations and diagnosis

1) Amending `REQUIRE_PATTERN` to include `requireType`, or otherwise adding dependencies for these `requireType` calls.

I tried this, but it wasn't fruitful because `requireType` is _supposed_ to avoid circular dependencies, and matching it with the Bazel build graph introduces those very dependencies. Thus, especially on `//closure/library/events`, errors can be solved until a circular dependency exists and halts further progress.

2) Suppressing the error

This is a terrible idea, but assuming the code makes it into the final binary, it _should_ work, right? No, because the volume of suppressions required to proceed essentially equals a full disabling of type checking.

**What should we do about this to maintain support for //closure/library?**

**Comment by sgammon** [comment]
@gkdn have you encountered / solved this issue for J2CL

**Comment by gkdn** [comment]
Sorry I don't have much experience with goog.requireType but my recollection of requireType is that it still requires the dependency to exist but it doesn't hold onto them during bundling / optimized output; which might be outdated.

@shicks Could you pls verify my recollection? Are these libs expected to have circular deps? What @sgammon refers here is the auto generated build rules for closure library that exists in rules_closure.

**Comment by sgammon** [comment]
@shicks AFAICT, `rules_closure` can't be used w/latest closure library unless this can get an answer

**Comment by gkdn** [comment]
@shicks is out of office. Adding @12wrigja and @kjin who could help.

**Comment by 12wrigja** [comment]
My understanding is that `requireType` helps avoid circular dependencies so long as the cycle exists entirely within a single build target (as it doesn't alleviate the cycle at the Bazel level).

Creating BUILD targets that are per-file (as indicated [here](https://github.com/bazelbuild/rules_closure/blob/a1a8128fe1a6b978c88822a3462f99bfcc7fd14a/closure/library/regenerate.py#L18)) is unlikely to work long-term. At best, I'd suggest one per package (which should avoid the issues with requireType).

**Comment by sgammon** [comment]
gotcha, thank you @12wrigja and @gkdn
