### ISSUE TITLE
Update Closure Compiler from `v20200614` to `v20210505`

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#525]
The current version of Closure Compiler hard-coded in the rules is quite old (`v20200614`):

https://github.com/bazelbuild/rules_closure/blob/6c344a0894f0645a0dc84f9cd0cf39d56bb01a24/closure/repositories.bzl#L656-L666

However, Closure Compiler has been releasing on a monthly cadence, and the latest version (at the time of this writing) is [`v20210505`](https://github.com/google/closure-compiler/releases/tag/v20210505
).

Could you please update to a more recent version to pick up the bug fixes since that release?

Or would you be open if I made a change to that file to update to the latest version? Not sure what your policy is on Closure Compiler updates, and what tests need to be run to validate the newer version of the compiler, besides the automated tests that will run as part of this repo's CI process.

Thanks!

**Comment by gkdn** [comment]
We are open to update of the version and will be happy to have a patch for it. These are no extra process other than automated tests passing.

However, in this particular case it seems like there are 2 issues that would need to be figured out, https://github.com/bazelbuild/rules_closure/issues/504 and https://github.com/bazelbuild/rules_closure/issues/516 for update. 

Let me know if you have any other questions.
