### ISSUE TITLE
Delete closure_js_deps

### ISSUE THREAD

**Issue by kjin** [bazelbuild/rules_closure#526]
Hi -- in Closure Library we are planning to remove the `depswriter.py` script, which is deprecated and superceded by the `closure-make-deps` binary that is part of the [`google-closure-deps`](https://www.npmjs.com/package/google-closure-deps) npm package.

The `closure_js_deps` rule here depends on `depswriter`, using it to output a `deps.js` file. I'd like to reimplement this to use the aforementioned `closure-make-deps` binary instead. This will involve either 

(1) checking in `google-closure-deps` (which is authored by Google) into this repo, or
(2) using some npm rule to load `google-closure-deps` in at compile time.

I'm not very familiar with the landscape of Bazel rules that have to do with npm, but my inclination given that Closure library and the compiler are already checked in here, is to also check in closure-deps.

**Comment by gkdn** [comment]
Actually Closure library and compiler is not checking into the repository. They are external deps.
And my recollection is that this repo doesn't depend on node or other means of executing tooling written in javascript.

So it seems like the options are:
1. Integrate with `rules_nodejs` to be able to use `google-closure-deps` (not sure how large of a dependency rules_nodejs or how much work that will be required)
2. Remove `closure_js_deps` rule in favor of bundling with the binary rule.

What are the use cases of `closure_js_deps`? Historically we and our customers treated as deps generation as deprecated and avoided it so I'm not sure how important it is. If not important, I would rather prefer just removing it.

**Comment by kjin** [comment]
deps.js is still used if code is being loaded with the debug loader, which I believe is still a current use case. I'm not sure if we can get rid of `closure_js_deps` outright.

I'll try looking into integrating with rules_nodejs. If all else fails, we could also move `depswriter` from Closure Library to here.

**Comment by gkdn** [comment]
> deps.js is still used if code is being loaded with the debug loader

For example non-of our customers use debug loader and the recent internal trend is to switch bundlers (due to performance reasons). So I think that's the question;  do people still care about it or is it something just for legacy?

**Comment by kjin** [comment]
There is [a bit of usage](https://github.com/search?l=Python&q=closure_js_deps+NOT+%22This+package+tests+the+behavior+of+closure_js_deps.%22+NOT+%2F%2Fjavascript%2Fwebdriver%2Fatoms%3Aall_js_for_testing+-filename%3Ahyperion2_deps_runfiles_test.sh&type=Code), but it's true that deps.js is indeed legacy and should be discouraged in the future.

@concavelenz pointed out that it might be good to remove this rule and allow users to fork the rule (i.e. rewrite it as their own) if needed. To that end, I'm now inclined to delete it, while linking here a GitHub repo or gist showing an example of how the rule could be forked.

**Comment by kjin** [comment]
I did an audit of the [uses of this rule](https://github.com/search?q=closure_js_deps&type=code), and it seems that for the most part people aren't using it, or they're using it in places where they're not needed. We can delete it, and if users do need it they can fork the rule (re-define it locally) and [the Python scripts](https://github.com/google/closure-library/tree/master/closure/bin/build) into their project.

**Comment by kjin** [comment]
So, if we do delete this -- should we create a release deprecating closure_js_deps first?

**Comment by gkdn** [comment]
> should we create a release deprecating closure_js_deps first?

Sound like a good idea.

**Comment by kjin** [comment]
@gkdn Hey Goktug -- is there an upcoming release for rules_closure planned? It would be great to have a release deprecating this rule first, and a subsequent one deleting it.

**Comment by gkdn** [comment]
https://github.com/bazelbuild/rules_closure/releases/tag/0.12.0

**Comment by kjin** [comment]
Thank you!

I think this particular issue is resolved -- I (or someone on my team) will circle back in a few months to get it deleted.
