### ISSUE TITLE
Runfiles can't be found when workspace() name is set

### ISSUE THREAD

**Issue by jart** [bazelbuild/rules_closure#53]
If I'm working on a *separate* project that uses Closure Rules as a dependency, and I put something like this in my `WORKSPACE` file:

```python
workspace(name = "LOLCATATTACK")
```

Then I get errors like this:

    bazel-out/host/bin/external/io_bazel_rules_closure/closure/templates/SoyToJsSrcCompiler: line 194: /usr/local/google/home/jart/.cache/bazel/_bazel_jart/e2f31d67319a8e487e516a36d39fd224/my-project/bazel-out/host/bin/external/io_bazel_rules_closure/closure/templates/SoyToJsSrcCompiler.runfiles/LOLCATATTACK/external/local_jdk/bin/java: No such file or directory

Maybe @kchodorow could clarify when this will be fixed?

**Comment by jart** [comment]
This appears to be related to https://github.com/bazelbuild/bazel/issues/1116

**Comment by kchodorow** [comment]
What version of Bazel are you using and where is Java under /usr/local/google/home/jart/.cache/bazel/_bazel_jart/e2f31d67319a8e487e516a36d39fd224/my-project/bazel-out/host/bin/external/io_bazel_rules_closure/closure/templates/SoyToJsSrcCompiler.runfiles/?

I tried doing:

```
$ touch x.soy
$ cat > BUILD <<EOF
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_template_js_library")

closure_template_js_library(
    name = "c",
    srcs = ["x.soy"],
)
EOF
$ cat > WORKSPACE <<EOF
workspace(name = "eg")
local_repository(
    name = "io_bazel_rules_closure",
    path = "/path/to/rules_closure",
)
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()
EOF
$ bazel build :c
```

and it worked for me.  Do you have have a repro?

**Comment by jart** [comment]
Actually I think this was fixed when I ran `bazel clean`. I forgot to close this. Please disregard.

Speaking of which, does Bazel take into consideration its own checksum when considering if cached content is valid? I've noticed that things get a little hairy when I upgrade Bazel but forget to clean.

**Comment by kchodorow** [comment]
It does, there was briefly a bug where it didn't notice if the workspace name changed (so it would leave the runfiles under .runfiles/old_name) but upgrading shouldn't require a `bazel clean` anymore.
