### ISSUE TITLE
rules_closure macos tests are failing in BazelCI

### ISSUE THREAD

**Issue by mai93** [bazelbuild/rules_closure#543]
rules_closure tests on Mac are failing with both Bazel@head and Bazel 4.2.1
Bazel 4.2.1: https://buildkite.com/bazel/rules-closure-closure-compiler/builds/1632#67a97508-5a2f-47ed-8746-aa1db00dfaec
Bazel@Head: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2244#1d80b36d-a762-420e-af8c-9d8203bacb00

Sample error log: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/67a97508-5a2f-47ed-8746-aa1db00dfaec/closure/stylesheets/test/defInChildTarget_getsPropagatedAutomatically/test.log

**Comment by gkdn** [comment]
Should be fix with https://github.com/bazelbuild/rules_closure/commit/01d45e9138d271077a03c278ff703524bcefd8e9
