### ISSUE TITLE
rules_closure 0.12.0 missing on Bazel mirror

### ISSUE THREAD

**Issue by mbrukman** [bazelbuild/rules_closure#555]
0.12.0 was released in June 2021, but it's still not available on Bazel mirror:

https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.12.0.tar.gz currently returns:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

Trying to download it using the changes in https://github.com/bazelbuild/rules_closure/pull/553 shows the error:

> WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/0.12.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

**Comment by gkdn** [comment]
@philwo

**Comment by Yannic** [comment]
@meteorcloudy could you help mirror this file please?

**Comment by meteorcloudy** [comment]
Done
