### ISSUE TITLE
Passing defs-define at commandline

### ISSUE THREAD

**Issue by nanarito** [bazelbuild/rules_closure#560]
This may end up being a better question on bazel itself, but is there a way to get bazel to pass defs in the bazel build command itself? I know you can have a BUILDfile with a rule and defs=['--define=X=y'] . I also know you can finnick with the bazel --define and then write a select() in the BUILDfile . Is there a way to just directly set this without changing the build, or to set up the build to pull the define from the environment?

**Comment by gkdn** [comment]
I am not aware of such feature but you can double check with Bazel folks.
