### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by roman-kashitsyn** [bazelbuild/rules_closure#585]
The latest release available is [`0.12`](https://github.com/bazelbuild/rules_closure/releases/tag/0.12.0). It was published more than two years ago and doesn't work with examples in the repo.

Could you please cut a new release?

**Comment by sgammon** [comment]
@roman-kashitsyn people often use this repo at `HEAD`, by pinning to a specific commit. i am not an author or contributor i am just hoping this advice helps

**Comment by fulldecent** [comment]
0.14.0 is releasted.

Recommending to close issue
