### ISSUE TITLE
closure_js_test support for foo_test_dom.html files

### ISSUE THREAD

**Issue by Dominator008** [bazelbuild/rules_closure#6]
Eg. https://github.com/google/wicked-good-xpath/blob/master/test/ancestor_test.html

Just wondering if these will be supported in addition to `*_test.js` files.
The relative paths referring to Closure Library's base.js might be an issue in the open source world.

**Comment by jart** [comment]
Internally there's two ways you can do it. If you have a test.js file, then you can add a test_dom.html to the srcs attribute, which will be used as part of the HTML document. We can support that. It was also possible to specify a test.html document, which is a feature I've never used where I think you can specify something like the closure library tests, where you manually specify the test runner and all that stuff. I'm not sure if we'd want to support that.

**Comment by jart** [comment]
It's also worth mentioning that the workaround I currently use, is I have my test insert the HTML content manually.

```javascript
/**
 * Adds specified HTML string to document.
 * @param {string} html
 */
function addToDocument(html) {
  goog.global.document.body.appendChild(
      goog.dom.safeHtmlToNode(
          goog.html.legacyconversions.safeHtmlFromString(html)));
};


function setUp() {
  addToDocument('<form><div id="bf"></div></form>');
}
```

Although I've been meaning to move away from this model and use the `foo_test_dom.html` structure, because our security team really doesn't like the idea of having raw HTML being inserted into a page like that, even for tests.

**Comment by jart** [comment]
This was mostly fixed in https://github.com/bazelbuild/rules_closure/commit/e140082ccf55b0839548d1c363dc191a31f7a39c which adds an `html` attribute to `closure_js_test`. In the future, we'll need to look into creating a better test runner that can do the `_dom.html` files from `srcs`.
