### ISSUE TITLE
Make closure_js_test compiled and more explicit

### ISSUE THREAD

**Issue by Dominator008** [bazelbuild/rules_closure#67]
Type safety should be encouraged in tests, https://github.com/bazelbuild/rules_closure#no-type-safety sounds misleading and is probably not the best practice.

Additionally, `closure_js_test` should be able to run both uncompiled and compiled. This can help finding Closure Compiler bugs.

**Comment by jart** [comment]
I agree. But it's not practical, because the Closure Library testing utilities don't work with type checking. If you want to mock something, you have to use a zillion `/** @type {foo} */` comments in your functions. It's a nightmare.

I would love nothing more than to make tests always run in uncompiled mode. They would run so fast that way. But a bug in PhantomJS is blocking this at the moment: https://github.com/ariya/phantomjs/issues/14028 It seems to be the biggest bug PhantomJS is facing. Yet no one has fixed it for years. It's probably not an easy problem to solve. Maybe I'll take a crack at it some day. But I probably won't have time anytime soon.

**Comment by Dominator008** [comment]
Then if tests don't use mocks we can have type safety?

Uncompiled by default is fine by me. I was talking about a parameter like `compiled = True` to allow tests to run both compiled and uncompiled.

**Comment by jart** [comment]
We could add a parameter like that. The user would be required to use `goog.testing.testSuite` rather than defining `testFoo` functions. Would that be an acceptable tradeoff to you?

**Comment by MatrixFrog** [comment]
"Mocks and typechecking don't play well together" is undeniably true but I definitely recommend that from that, you draw the conclusion "Avoid mocks when possible" and not "Don't bother typechecking your test code"

**Comment by jart** [comment]
In that case @MatrixFrog, would you argue that type checking should be the default mode for `closure_js_test`?

**Comment by MatrixFrog** [comment]
I think so. As you probably know, switching the default for the similar Google-internal rule will likely never happen because there's just too much non-typecheckable test code already there. But if there's going to be a new set of rules then it would probably be nice to set that as the default.

**Comment by Dominator008** [comment]
@jart For running tests compiled, I assume `goog.require('goog.testing.jsunit');` also works? I don't mind explicitly adding a `goog.require` statement. In fact I prefer the explicitness so that it's clear that the assert functions are defined.

**Comment by MatrixFrog** [comment]
I would agree, this seems like a clear "explicit is better than implicit" kind of situation. This is why our linter has a special exception for  goog.testing.jsunit

**Comment by jart** [comment]
I agree with the feedback both of you are giving right now, on pretty much all points. My only concern is I want to help mocking be less painful in type checking mode. Would it be possible for us to add `@suppress` of some sort to the Closure Library mocking functions so they don't cause too many headaches? That way we get the best of both worlds.

So here's the strategy:

1. Make type checking the default.
2. Provide option to turn type checker off.
3. Have JsChecker verify that `goog.require('goog.testing.{jsunit,asserts}')` are in the test files.

Sound good so far?

**Comment by Dominator008** [comment]
@jart Sounds good to me.
