### ISSUE TITLE
Unable to import rules

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/rules_closure#7]
Built bazel from HEAD this morning, and tried following instructions in the readme to import the closure rules. I get this error:
`ERROR: no such package '@io_bazel_rules_closure//closure': Invalid branch, tag, or commit: Ref tags/0.0.1 can not be resolved.`

The relevant portion of my workspace file:
```
git_repository(
    name = "io_bazel_rules_closure",
    remote = "https://github.com/bazelbuild/rules_closure.git",
    tag = "0.0.1",
)

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_repositories")
closure_repositories()
```

**Comment by jart** [comment]
We haven't tagged a release yet. Try changing to the latest commit.

**Comment by jart** [comment]
Release added https://github.com/bazelbuild/rules_closure/releases/tag/0.0.1

You should now be able to use that tag.
