### ISSUE TITLE
Need concrete examples of usage

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/rules_closure#8]
It would be helpful to add some concrete examples of how to use the closure rules in either the readme (which is already long, so maybe not) or an examples subdirectory that is linked to by the readme.

**Comment by jart** [comment]
The closest thing we have to concrete examples at the moment are the test directories:

- https://github.com/bazelbuild/rules_closure/tree/master/closure/testing/test
- https://github.com/bazelbuild/rules_closure/tree/master/closure/compiler/test
- https://github.com/bazelbuild/rules_closure/tree/master/closure/library/test
- https://github.com/bazelbuild/rules_closure/tree/master/closure/stylesheets/test

I plan on creating more comprehensive examples soon. I also want to make like a guestbook application or something to show how to build a proper production app that uses all this functionality.

For further examples on using these rules, you can also check out the you know what codebase.
