### ISSUE TITLE
Repeat build binary output fails following a successful run

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#84]
I've been able to successfully build an ADVANCED mode compiled binary output via this [test repository](https://github.com/pubref/rules_closure_demoapp).  However, repeating the last command `bazel build //:client_bin` fails with the given error.  One would assume that bazel would know nothing has changed and exit 0 immediately.  However, there is some process that is removing the `bazel-bin/client_bin.js` file and causing a problem.  

The workaround is trivial: make a change to any input *.js file and bazel will rebuild the output successfully again.  Might be something I'm doing wrong.

```
pcj@carotid:~/github/rules_closure-getting-started$ ~/bin/bazel build //:client_bin
INFO: Found 1 target...
Target //:client_bin up-to-date:
  bazel-bin/client_bin.js
INFO: Elapsed time: 14.067s, Critical Path: 13.90s
pcj@carotid:~/github/rules_closure-getting-started$ ~/bin/bazel build //:client_bin
INFO: Found 1 target...
ERROR: /Users/pcj/github/rules_closure-getting-started/BUILD:24:1: Compiling 809 JavaScript files to client_bin.js failed: compiler failed: error executing command bazel-out/local-fastbuild/bin/external/io_bazel_rules_closure/closure/compiler/compiler '--js_output_file=bazel-out/local-fastbuild/bin/client_bin.js' ... (remaining 826 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
ERROR - Cannot read: bazel-bin/client_bin.js

ERROR - Cannot read: bazel-out/local-fastbuild/bin/client_bin.js

2 error(s), 0 warning(s)
Target //:client_bin failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.225s, Critical Path: 2.01s
```

**Comment by jart** [comment]
This sort of build nondeterminism is strange. Would you be able to share your build file? Or better yet, would you be able to zip up something that reproduces the problem? If so, I'll be happy to take a look.

**Comment by jart** [comment]
Also does the problem go away if you `bazel clean`?

**Comment by pcj** [comment]
BUILD file is https://github.com/pubref/rules_closure_demoapp/blob/master/BUILD.

Bazel clean does fix the problem. But so does just running the command again.  So, repeating the same build command over and over again just alternates between success and failure as above.

**Comment by pcj** [comment]
This is old, will re-open if I see it again.
