### ISSUE TITLE
Consider js2-closure integration

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#86]
With clang-format based style enforcement (https://github.com/bazelbuild/rules_closure/pull/85) out for review we should consider also adding https://github.com/jart/js2-closure support. The two seem like they could work very well together as a save hook from an editor. If rules_closure could automatically regenerate the "provides index" the entire setup would be very user friendly I think.

**Comment by jart** [comment]
I'm not sure if it would be appropriate to integrate js2-closure here. That project is written to take a deeply personal solution (i.e. hacky) to getting the set of provided namespaces. It's not something I could universalize into this build system.

If I wanted to create a universal solution, I would probably find some way to build a Java app that runs as a daemon which uses Closure Compiler to understand things on the fly. Then provide deep IDE functionality. But we'll probably have to wait for Bazel's IDE situation to improve.

**Comment by hochhaus** [comment]
Very fair points.

I have not looked at the implementation of js2-closure but isn't all of the information required for the "provides index" included in deps.js? If so, possibly generating deps.js files automatically for all libraries would be the only support required from rules_closure.

I'm also very happy waiting for a cleaner bazel solution though. We can close this if you like.

**Comment by jart** [comment]
In theory a deps.js would be able to do it. But it would just be a different flavor of the same hack. It wouldn't offer much value on top of the current kludge. You might also want your js2-closure index to include a superset of namespaces that reflects multiple projects you're working on, so you can quickly hop back and forth.
