### ISSUE TITLE
Bump to 0.1.1

### ISSUE THREAD

**Issue by pcj** [bazelbuild/rules_closure#87]
...or whatever your next release label is.  The README.md is a little behind: I was struggling to figure out why closure_proto_js_library could not be found until I realized it does not exist in 0.1.0.  Worked after I upgraded to: 

```
git_repository(
    name = "io_bazel_rules_closure",
    remote = "https://github.com/bazelbuild/rules_closure.git",
    commit = "80d493d5ffc3099372929a8cd4a301da72e1b43f"
)
```

**Comment by jart** [comment]
Done. https://github.com/bazelbuild/rules_closure/releases/tag/0.2.0

https://groups.google.com/forum/#!topic/closure-rules-announce/7-iXVqx1EL8 <-- please subscribe to that list if you haven't already.
