### ISSUE TITLE
Can't run on App Engine

### ISSUE THREAD

**Issue by wolfgangmeyers** [bazelbuild/rules_closure#88]
The current version of the soy library that is included by the closure rules library is built with JDK 8, which prevents any consumers of this library from deploying to the traditional GAE platform. Could you consider rolling back to 2015-04-10 or forward to the next version if it switches back to using JDK 7?

**Comment by jart** [comment]
This was reported to Closure Templates back in March: https://github.com/google/closure-templates/issues/80
