### ISSUE TITLE
rules_protobuf project?

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#89]
Sorry for opening this issue on rules_closure but I don't know where else to put it.

When adding JSPB support https://github.com/bazelbuild/rules_closure/pull/68, @jart asked:

> @damienmg @kchodorow Should we start a new bazelbuild/rules_protobuf project?

What is the current thinking on a rules_protobuf project?

My reason for asking is that I'm working on a set of Go PB rules and I would like to be able to contribute them to the bazel community in a shared location. I could attempt to put them in rules_go, however it seems like moving all of the protobuf rules to a central repo may be cleaner.

**Comment by jart** [comment]
I spoke with Damien and the rules are probably going to be hosted in https://github.com/google/protobuf/blob/master/protobuf.bzl or somewhere in the google/protobuf repo. Then the various rules projects, e.g. Closure Rules, will implements *aspects* that define language specific bindings. Someone at Google is working on it. But I'm not sure when it's going to be ready.

**Comment by jart** [comment]
Yeah right now everyone seems to be using their own local workarounds. Which I guess is fine for now.

**Comment by jart** [comment]
Although one thing we need to do, is the internal design doc for the proto build redesign is naming the language-specific targets lang_proto_library (rather than proto_lang_library.) So we should probably rename our rule to be closure_js_proto_library, to fit with this convention. We should also do the same thing with the template rules probably.

**Comment by jart** [comment]
I'd also like to move //protobuf -> //closure/protobuf now that we know it's going to be a permanent part of this codebase, once it's converted to an aspect in the future.

**Comment by hochhaus** [comment]
Good idea. Change sent.
