### ISSUE TITLE
suppress of diagnostic group triggers "contains superfluous suppress codes" error

### ISSUE THREAD

**Issue by hochhaus** [bazelbuild/rules_closure#97]
Using a `closure_js_library()` suppress for a diagnostic group (eg: `nonStandardJsDocs`) triggers a `contains superfluous suppress codes` error message even when the suppression hides warnings. For example:

```
ahochhaus@ahochhaus-pc:~/ll$ cat test/BUILD 
load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_library")

closure_js_library(
  name = "example_lib",
  srcs = ["example.js"],
  deps = [
      "@io_bazel_rules_closure//closure/library",
  ],
  suppress = [
    "nonStandardJsDocs",
  ],
  visibility = ["//visibility:public"],
)
ahochhaus@ahochhaus-pc:~/ll$ cat test/example.js 
/**
 * @typedef {{
 *   timestamp: number,
 *   id: number,
 *   type: string,
 *   fromAdaptation: boolean
 * }}
 *
 * @property {number} timestamp
 *   The timestamp the choice was made, in seconds since 1970
 *   (i.e. Date.now() / 1000).
 * @property {number} id
 *   The id of the stream that was chosen.
 * @property {string} type
 *   The type of stream chosen ('audio', 'text', or 'video')
 * @property {boolean} fromAdaptation
 *   True if the choice was made by AbrManager for adaptation; false if it
 *   was made by the application through selectTrack.
 * @exportDoc
 */
shakaExtern.StreamChoice;
ahochhaus@ahochhaus-pc:~/ll$ bazel build test/...
INFO: Found 1 target...
ERROR: /home/ahochhaus/ll/test/BUILD:3:1: Checking 1 JS files in //test:example_lib failed: namespace-sandbox failed: error executing command /home/ahochhaus/.cache/bazel/_bazel_ahochhaus/9b0316414c69160d24362f2991b802bb/ll/_bin/namespace-sandbox ... (remaining 11 argument(s) skipped).
ERROR - Build rule (//test:example_lib) contains superfluous suppress codes: nonStandardJsDocs

1 error(s), 0 warning(s)

Target //test:example_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.820s, Critical Path: 0.65s
ahochhaus@ahochhaus-pc:~/ll$ sed -i 's/"nonStandardJsDocs/#"nonStandardJsDocs/g' test/BUILD 
ahochhaus@ahochhaus-pc:~/ll$ bazel build test/...
INFO: Found 1 target...
INFO: From Checking 1 JS files in //test:example_lib:
test/example.js:19: WARNING - Parse error. illegal use of unknown JSDoc tag "exportDoc"; ignoring it
 * @exportDoc
   ^

0 error(s), 1 warning(s)

Target //test:example_lib up-to-date (nothing to build)
INFO: Elapsed time: 0.832s, Critical Path: 0.66s
```

The superfluous suppress error should only be triggered when no warnings or errors are suppressed.

P.S. Sorry for my absence. I intend to resume my clang format work soon...

**Comment by hochhaus** [comment]
One other question: When not suppressing `nonStandardJsDocs` should JsChecker report the unknown JSDoc tag as an error (instead of a warning)?

More generally, which diagnostic group should be warnings? On some level it seems cleaner to make every diagnostic group either be (i) an error (forcing the explicit suppression when necessary) or (ii) disabled entirely.

**Comment by jart** [comment]
Welcome back. No need for apologies. The way I see it, you're donating your time to this project. I am grateful for each and every hour you spend helping out, regardless of when you choose to do it.

If this were a `closure_js_binary` rule then the solution would be to say `defs = ["--extra_annotation_name=exportDoc"]`. But we don't have that for JsChecker. Suppression is the only option. And it's broken. But I think I know why. I'll mail out a PR in a second.

Whether it should be a warning or an error is a good question. When I finally get around to unifying the suppression system across binary/library rules, we're all going to have to put a lot of thought into that. There's a lot of error categories we'll need to comb through. (See DiagnosticCodes.java in Closure Compiler.)
